---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xgjoy0308.
--- DateTime: 2023/7/5 19:02
---

local ChannelDefine = {}

ChannelDefine.Channel_Development = 0
ChannelDefine.Channel_Netease = 1

local channelDic = {

    [ChannelDefine.Channel_Development] = "",
    [ChannelDefine.Channel_Netease] = "netease",
}


ChannelDefine.ChannelDic = channelDic

return ChannelDefine