---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xgjoy0308.
--- DateTime: 2023/7/25 15:19
---

local NetEaseDefine = {}

-- 问卷调查地址  "https://research.easebar.com/htmls/73d6cc/paper.html"
NetEaseDefine.QUESTIONNAIRE_URL = "https://research.easebar.com/htmls/lpt9q5/paper.html"

-- 用户协议
NetEaseDefine.COMPACT_URL_EN = "https://protocol.unisdk.easebar.com/release/latest_v48.tw.json"
NetEaseDefine.COMPACT_URL_CHS = "https://protocol.unisdk.easebar.com/release/latest_v48.tw.json"
NetEaseDefine.COMPACT_URL_DEFAULT = "https://protocol.unisdk.easebar.com/release/latest_v48.tw.json"

-- 正式支付地址
NetEaseDefine.UNISDKJFGAS3_URL = "https://mgbsdknaeast.matrix.easebar.com/ma155naxx2gb/sdk/"
-- 测试支付地址
NetEaseDefine.UNISDKJFGAS3_URL_TEST = "https://mgbsdksgtest.matrix.easebar.com/ma155naxx2gb/sdk/"

NetEaseDefine.AC_SDK_GAME_ID_IOS = "ios_ma155na "
NetEaseDefine.AC_SDK_GAME_ID_ANDROID = "android_ma155na"
NetEaseDefine.AC_SDK_KEY = "a19zuobpni1nox7x"

return NetEaseDefine