---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xgjoy0308.
--- DateTime: 2023/11/28 20:07
---
---


local LanguageConst = require("Game/Logic/LanguageConst")
local SDKReportPlayer = {}
local self = SDKReportPlayer

--举报时间间隔
SDKReportPlayer.INTERVAL_TIME = 600
SDKReportPlayer.REPORT_LEVEL = 30

SDKReportPlayer.TYPE_FROM_PLAYER_INFO = 1--玩家详情
SDKReportPlayer.TYPE_FROME_GUILD_INFO = 2--工会详情

--这些不需要翻译,上报sdk需要中文
SDKReportPlayer.typeEnum = {
    [1] = {'昵称不雅','签名不雅','言行不雅','举报诈骗','举报外挂','违法内容','广告刷屏','抄袭剽窃','举报其他'},
    [2] = {'公会昵称','公会规范','公会消息','言行不雅','举报诈骗','举报外挂','违法内容','广告刷屏','抄袭剽窃','举报其他'}
}

--这些不需要翻译,上报sdk需要中文
SDKReportPlayer.channelEnum = {
    [SDKReportPlayer.TYPE_FROM_PLAYER_INFO] = '玩家详情',
    [SDKReportPlayer.TYPE_FROME_GUILD_INFO] = '工会详情',
}


function SDKReportPlayer.ReportPlayer(content)
    --if Util.Account.PlayerLv() < SDKReportPlayer.REPORT_LEVEL then
    --    MsgManager.notice(LanguageConst.Report1)--您的等级不足，请先升到30级
    --    return
    --end
    local channelType = content.channel
    local key = "SDKReportPlayerTime_" .. Util.Account.PlayerUid()
    local value = LuaCallCs.PlayerPrefs.GetInt(key)
    if value > 0 then
        local deltaTime = TimeUtils.getServerTime() - value
        if deltaTime < SDKReportPlayer.INTERVAL_TIME then
            --您点的太快了，请%d秒后再进行举报
            MsgManager.notice(string.format(LanguageConst.Report2,SDKReportPlayer.INTERVAL_TIME - deltaTime))
            return
        end
    end
    content.type = SDKReportPlayer.typeEnum[content.channel][content.type]
    content.chat = ""
    --精确公会相关的举报内容
    if content.channel == SDKReportPlayer.TYPE_FROME_GUILD_INFO then

    elseif content.channel == SDKReportPlayer.TYPE_FROM_PLAYER_INFO then
        if content.type == SDKReportPlayer.typeEnum[1][1] then--昵称不雅
            content.chat = content.nicheng
            content.nicheng = nil
        elseif content.type == SDKReportPlayer.typeEnum[1][2] then--签名不雅
            content.chat = content.qianming
            content.qianming = nil
        end
    end
    print('Report Player Chat = '..content.chat)
    content.channel = SDKReportPlayer.channelEnum[content.channel]
    local privateChat = DataCoreTools.getReportPrivateMessData(content.uid2)
    print('Report Player----'..table.dump(content),privateChat)
    SendHandlers.ReqReportServer({},"ReportPlayer",ClientUtils.table2String(content),channelType,privateChat)
    LuaCallCs.PlayerPrefs.SetInt(key,TimeUtils.getServerTime())
    MsgManager.notice(LanguageConst.Report3)--感谢您的支持，我们会尽快处理
end

return SDKReportPlayer