local EventConst = {
    -------------------------------网络相关事件---------------------------------
    --虚拟http发送事件
    HTTP_MESSAGE_SEND = "HTTP_MESSAGE_SEND",
    --网络消息发送事件
    NETWORK_MESSAGE_SEND = "NETWORK_MESSAGE_SEND",
    --网络消息接收事件
    NETWORK_MESSAGE_RECV = "NETWORK_MESSAGE_RECV",

    --SvrList
    SERVER_LIST_CHANGED = "SERVER_LIST_CHANGED",

    SELECTED_SERVER_CHANGED = "SELECTED_SERVER_CHANGED",

    --登录完成
    ACCOUNT_LOGIN_FINISH = "ACCOUNT_LOGIN_FINISH",

    --Zone断线
    ZONE_SERVER_DISCONNECT = "ZONE_SERVER_DISCONNECT",

    -------------------------------游戏状态相关事件---------------------------------
    --状态绑定场景加载完
    --GAME_STATE_SCENE_LOADED = "GAME_STATE_SCENE_LOADED",
    --状态加载完
    --GAME_STATE_LOADED = "GAME_STATE_LOADED",
    --状态退出
    GAME_STATE_EXIT = "GAME_STATE_EXIT",
    --场景加载完
    --场景卸载时--
    SCENE_UNLOAD = "SCENE_UNLOAD",
    -------------------------------消息相关事件---------------------------------
    --自己发言成功
    MSG_SELF_SENDED = "MSG_SELF_SENDED",
    --收到消息
    MSG_RECEIVE_NEW = "MSG_RECEIVE_NEW",

    ITEM_UPDATE = "ITEM_UPDATE",

    CONDITION_LOCK_CHANGED = "CONDITION_LOCK_CHANGED",

    LEVEL_CHANGE = "LEVEL_CHANGE",

    TIME_COUNTER_UPDATE = "TIME_COUNTER_UPDATE",

    NEWBIE_TASK_UPDATE = "NEWBIE_TASK_UPDATE",
    -- 获得的货币飞到货币栏
    MONEY_FLY = "MONEY_FLY",
    -- 新的一天
    NEW_DAY = "NEW_DAY",
    -- 商品信息（包括游戏逻辑和平台的信息）载入结束，载入结果可能为失败
    RECHARGE_PRODUCTS_LOAD_END = "RECHARGE_PRODUCTS_LOAD_END",
    -- 需要重新刷新自定义阴影，一般是ModelStage关闭的情况
    REFRESH_SHADOW = "REFRESH_SHADOW",
    -- RemoteConfig加载
    REMOTE_CONFIG_LOADED = "REMOTE_CONFIG_LOADED",
    -- 充值商品发放
    RECHARGE_DELIVER = "RECHARGE_DELIVER",
    -- 跳转(guideId, sourceUIName, ... )
    JUMP_GUIDE = "JUMP_GUIDE",
    -- 添加跑马灯消息
    ADD_SCROLL_TXT = "ADD_SCROLL_TXT",
    -- 刷新问卷调查数据
    REFRESH_QUESTIONINFO = "REFRESH_QUESTIONINFO",
    -- 完成问卷调查
    COMPLETE_QUESTIONINFO = "COMPLETE_QUESTIONINFO",
    CLOSE_WEBVIEW = "CLOSE_WEBVIEW",
    --选择了拼图奖励
    SELECT_PUZZLE_REWARD = "SELECT_PUZZLE_REWARD",
    --随机了拼图格子
    RANDOM_PUZZLE_GRID = "RANDOM_PUZZLE_GRID",
    --拼图新的轮次
    NEW_PUZZLE_ROUND = "NEW_PUZZLE_ROUND",
    --关闭界面
    CLOSE_CURRENT_UI = "CLOSE_CURRENT_UI",
    --刷新当前界面
    UPDATE_CURRENT_UI = "UPDATE_CURRENT_UI",
    --是否显示btnRight
    SET_BTN_STATE = "SET_BTN_STATE",
    --设置btn的alpha
    SET_BTN_STATE_ALPHA = "SET_BTN_STATE_ALPHA",
    --邮件到期
    MAIL_TIME = "MAIL_TIME",
    --app跳转
    SDK_TO_APP = "SDK_TO_APP",
    --刷新社区按钮
    UPDATE_SOCIAL_BTN = "UPDATE_SOCIAL_BTN",
    --刷新首充按钮
    UPDATE_FIRST_RECHARGE = "UPDATE_FIRST_RECHARGE",

    CHANGE_ACTIVITY_DATA = "CHANGE_ACTIVITY_DATA",

    UPDATE_MAIN_STORY = "UPDATE_MAIN_STORY",

    UPDATE_MAIN_TASK = "UPDATE_MAIN_TASK",

    -------------------------------切屏相关事件---------------------------------
    PORTRAIT = "PORTRAIT",
    LANDSPACE = "LANDSPACE",

    -------------------------------网络数据导致UI刷新 By HaoRen -------------------
    CDC_BASE_RES = "BASERESOURE_TOPUI",
    CDC_ITEMS = "ITEMS_CHANGED",
    CDC_ACTIVITYMILL = "ACTIVITYSHOP_DATA_CHANGED", --更新非付费商城商品
    CDC_MILL = "SHOP_DATA_CHANGED", --更新商城商品
    CDC_MILLPANEL = "CDC_MILLPANEL", --更新商城界面
    CDC_HEROLOCK = "CDC_HEROLOCK",
    CDC_HEROUP = "CDC_HEROUP",
    CDC_HEROLVDOWN = "CDC_HEROLVDOWN", --等级重置
    CDC_HEARUPSTAR = "CDC_HEARUPSTAR", --英雄升星回调
    --CDC_HEARUPSTARMULTIPLE = "CDC_HEARUPSTARMULTIPLE", --一键或智能升星回调
    CDC_HEROSTARREVERT = "CDC_HEROSTARREVERT", --英雄降星
    CDC_OPERATEMAIL = "CDC_OPERATEMAIL", --邮件事件
    CDC_HEROSTARUP = "CDC_HEROSTARUP", --邮件事件
    CDC_HEROEQUIP = "CDC_HEROEQUIP", --英雄装备操作
    CDC_RECRUITSTATUS = "CDC_RECRUITSTATUS", --招募状态status
    CDC_RECRUIT = "CDC_RECRUIT", --招募英雄
    CDC_RECRUIT_Protect = "CDC_RECRUIT_Protect", --招募英雄成就数据
    CDC_RECRUIT_2 = "CDC_RECRUIT_2", --魂石招募
    CDC_RECRUIT_3 = "CDC_RECRUIT_3", --魂石up招募-占星值
    CDC_RECRUIT_CALL_REWARD = "CDC_RECRUIT_CALL_REWARD", --刷新召唤奖励
    CDC_RECRUITCAMPWISH = "CDC_RECRUITCAMPWISH", --阵营心愿英雄
    CDC_RECRUITLIMITEDHERO = "CDC_RECRUITLIMITEDHERO", --限时UP奖励Panel
    CDC_RECRUITSEVEN = "CDC_RECRUITSEVEN", --招募英雄20抽
    CDC_RECRUITRECORD = "CDC_RECRUITRECORD", --招募记录
    CDC_RECRUITRECORD_RESULT = "CDC_RECRUITRECORD_RESULT", --200抽10结果
    CDC_EQUIPLVUP = "CDC_EQUIPLVUP", --装备升级
    CDC_UIHEROALBUM = "CDC_UIHEROALBUM", --图鉴刷新
    CDC_UIAMENDMENTNOTICEHEAD = "CDC_UIAMENDMENTNOTICEHEAD", --头像刷新
    CDC_UITASK = "CDC_UITASK", --主线任务和成就刷新
    CDC_REPEATABLETASK = "CDC_REPEATABLETASK", --每日和周长任务
    CDC_STEPTOWERSWEEP = "CDC_STEPTOWERSWEEP", --升阶塔刷新
    CDC_STEPTOWESHOWREWARD = "CDC_STEPTOWESHOWREWARD", --升阶塔扫荡经验
    CDC_FRIENDS = "CDC_FRIENDS", --好友刷新
    CDC_REQUEST = "CDC_REQUEST", --好友申请刷新
    CDC_ROLELV = "CDC_ROLELV", --玩家等级经验
    CDC_MONUMENT = "CDC_MONUMENT", --圣山成就
    CDC_MONUMENTPANEL = "CDC_MONUMENTPANEL", --圣山Panel成就
    CDC_RANKING = "CDC_RANKING", --排行榜
    CDC_RANKING_OK = "CDC_RANKING_OK", --排行榜获得数据
    CDC_DIALOG = "CDC_DIALOG", --剧情
    CDC_DIALOG_ACT = "CDC_DIALOG_ACT",
    --CDC_UPWARPDATA = "CDC_UPWARPDATA",--刷新扭曲空间
    CDC_SWEEPWARP = "CDC_SWEEPWARP", --扫荡扭曲空间
    CDC_DUNGEON = "CDC_DUNGEON", --地牢s
    CDC_TEAMBOOK = "CDC_TEAMBOOK", --系列收藏
    CDC_EQUIPQUALITYUP = "CDC_EQUIPQUALITYUP", --装备升品
    CDC_EQUIPSELL = "CDC_EQUIPSELL", --装备出售
    CDC_ALLGUILD = "CDC_ALLGUILD", --获取全部公会
    CDC_GUILDINFO = "CDC_GUILDINFO", --获得公会信息
    CDC_REFUIGUILDTASK = "CDC_REFUIGUILDTASK", --公会任务
    CDC_INVITATIONMESSAGE = "CDC_INVITATIONMESSAGE", --刷新受邀消息
    CDC_HEROARTIFACT = "CDC_HEROARTIFACT", --英雄神器操作
    CDC_HEROPET = "CDC_HEROPET", --宠物操作
    CDC_HEROUPDATA = "CDC_HEROUPDATA", --英雄界面刷新一次
    CDC_RENAME = "CDC_RENAME", --起名
    CDC_PLAYERINFO = "CDC_PLAYERINFO", --改名、改性别、改签名
    CDC_ASYNC_CD = "CDC_ASYNC_CD", --竞技场积分赛刷新	
    CDC_ASYNC_REFRESHUI = "CDC_ASYNC_REFRESHUI", --竞技场段位信息刷线
    CDC_ASYNC_ARENAMATCHINFO = "CDC_ASYNC_ARENAMATCHINFO", --竞技场积分赛刷新
    CDC_ASYNC_INFO = "CDC_ASYNC_INFO", --布阵信息刷新
    CDC_ASYNC_INFO_UPDATE = "CDC_ASYNC_INFO_UPDATE", --请求到阵容信息后刷新
    CDC_ARTIFACTLEVELUP = "CDC_ARTIFACTLEVELUP", --神器升级
    CDC_ARTIFACTADVANCED = "CDC_ARTIFACTADVANCED", --神器突破
    CDC_ACTIVITY_DATA = "CDC_ACTIVITY_DATA", --获取全部活动数据
    CDC_ACTIVITY_DATA_REDPOINT = "CDC_ACTIVITY_DATA_REDPOINT", --获取全部活动数据
    CDC_ACTIVITY_REFRESHDATA = "CDC_ACTIVITY_REFRESHDATA", --许愿活动结束刷新主界面
    CDC_USE_ITEM = "CDC_USE_ITEM", --使用道具
    CLEAR_QUICK_LV = "CLEAR_QUICK_LV", --关闭快速升级倒计时
    CDC_ARENA_RECOAD = "CDC_ARENA_RECOAD", --竞技场积分赛战报
    CDC_DICE_TASK_RWD = "CDC_DICE_TASK_RWD", --大富翁获取任务奖励
    CDC_DICE_COM = "CDC_DICE_COM", --大富翁普通骰子
    CDC_DICE_SPE = "CDC_DICE_SPE", --大富翁特殊骰子
    CDC_DICE_ACT = "CDC_DICE_ACT", --大富翁获取奖励
    CDC_CHAT_HISTORY = "CDC_CHAT_HISTORY", --聊天记录
    CDC_CHAT_ACTION = "CDC_CHAT_ACTION", --收到聊天消息
    CDC_DICE_ITEM = "CDC_DICE_ITEM", --大富翁奖励
    CDC_DICE_DESTROY = "CDC_DICE_DESTROY", --关闭界面 大富翁专用
    CDC_SERVER_LIST_UPDATED = "CDC_SERVER_LIST_UPDATED", -- 服务器列表刷新
    CDC_SERVER_SELECTED = "CDC_SERVER_SELECTED", -- 服务器选择
    SDK_CANCLE_LOGIN = "SDK_CANCLE_LOGIN", -- SDK取消登录操作
    ACCOUNT_LOGIN_SUCCESS = "ACCOUNT_LOGIN_SUCCESS", -- 账号登录成功
    CDC_HERO_SELL = "CDC_HERO_SELL", --英雄献祭出售
    CDC_HERO_SKill_RESET = "CDC_HERO_SKill_RESET", --技能重置
    CDC_GAME_RESET = "CDC_GAME_RESET", -- 游戏重置事件
    CDC_HERO_SKIN = "CDC_HERO_SKIN", -- 英雄换装
    CDC_BOSS_CD = "CDC_BOSS_CD", --无尽之战
    CDC_RELIC_PET_UPGRADE = "CDC_RELIC_PET_UPGRADE", --宠物升级
    CDC_BAG_ADD = "CDC_BAG_ADD", --背包扩展
    CDC_REFRESH_BONFIRE_HERO = "CDC_REFRESH_BONFIRE_HERO", --刷新篝火英雄
    CDC_ODYSSEY_REFRESH = "CDC_ODYSSEY_REFRESH", --奥德赛数据刷新
    CDC_ODYSSEY_QUIT = "CDC_ODYSSEY_QUIT", --奥德赛退出副本
    CDC_DS_REFRESH = "CDC_DS_REFRESH", --龙眠数据刷新
    CDC_DS_QUIT = "CDC_DS_QUIT", --龙眠退出副本
    CDC_ASYNC_SWEEP = "CDC_ASYNC_SWEEP", --竞技场扫荡
    CDC_RENTTASK = "CDC_RENTTASK", --悬赏任务
    CDC_BATTLEDRAGONEGG_RES = "CDC_BATTLEDRAGONEGG_RES", --战龙蛋数据回传
    CDC_BATTLEDRAGON_RES = "CDC_BATTLEDRAGON_RES", --战龙数据回传
    CDC_BATTLEDRAGON_UP = "CDC_BATTLEDRAGON_UP", --战龙数据回传
    CDC_BATTLEDRAGON_NEW = "CDC_BATTLEDRAGON_NEW", --战龙孵化成功
    CDC_BATTLEDRAGON_STEP_UP = "CDC_BATTLEDRAGON_STEP_UP", --战龙进阶成功
    CDC_DARKCRYSTAL = "CDC_DARKCRYSTAL", --黯晶
    CDC_EQUIPANDARTIFACTSELECT = "CDC_EQUIPANDARTIFACTSELECT",
    CDC_INIT_WISHLIST = "CDC_INIT_WISHLIST", --初始化心愿单
    CDC_UPDATE_TICKET = "CDC_UPDATE_TICKET", --刷新入场券或面包
    CDC_ACTIVITY_ONLINE_REWARD = "CDC_ACTIVITY_ONLINE_REWARD", --在线奖励活动
    CDC_GUILD_SHOP = "CDC_GUILD_SHOP",
    CDC_UPDATE_SELFPLAYERINFO = "CDC_UPDATE_SELFPLAYERINFO", --更新自己的玩家信息
    CDC_POST_PLAYERINFO = "CDC_POST_PLAYERINFO", --获取玩家信息
    CDC_CARNIVAL = "CDC_CARNIVAL", --七日豪礼抽奖
    CDC_CARNIVAL_SHOP = "CDC_CARNIVAL_SHOP", --七日豪礼礼包购买

    CDC_GUILD_REWARDBOX = "CDC_GUILD_REWARDBOX", --公会宝箱
    CDC_GUILD_BOSSRANK = "CDC_GUILD_BOSSRANK", --公会Boss排行榜


    --个人信息
    CDC_INFODATA_RED = "CDC_INFODATA_RED",
    CDC_INFODATA = "CDC_INFODATA", --个人信息服务器推送数据刷新


    --魂石
    CDC_EQUIP_SOULSTONE = "CDC_EQUIP_SOULSTONE", --装备魂石
    CDC_ACTIVITY_SOULSTONE_DRAW = "CDC_ACTIVITY_SOULSTONE_DRAW", --魂石抽奖
    CDC_ACTIVITY_SOULSTONE_RANK = "CDC_ACTIVITY_SOULSTONE_RANK", --魂石排行榜


    ------纹章
    CDC_EMBLEM_STRENGTH = "CDC_EMBLEM_STRENGTH", --纹章强化
    CDC_EMBLEM_PUTON = "CDC_EMBLEM_PUTON", --纹章穿戴
    CDC_EMBLEM_PUTONALL = "CDC_EMBLEM_PUTONALL", --纹章一键穿戴
    CDC_EMBLEM_TAKEOFF = "CDC_EMBLEM_TAKEOFF", --纹章卸下
    CDC_EMBLEM_TAKEOFFALL = "CDC_EMBLEM_TAKEOFFALL", --纹章一键卸下
    CDC_EMBLEM_LOCK = "CDC_EMBLEM_LOCK", --纹章锁定

    --vip特权
    CDC_PLAYER_VIP = "CDC_PLAYER_VIP", --vip特权


    CDC_UPDATE_REDPOINT_STATE = "CDC_UPDATE_REDPOINT_STATE", --更新红点状态

    CDC_NAMECARDS = "CDC_NAMECARDS",

    ------ 利姆鲁系统 ------    
    CDC_RIMURU_EVOLVE = "CDC_RIMURU_EVOLVE", --利姆鲁-魔王之路晋升
    CDC_RIMURU_UABILITY = "CDC_RIMURU_UABILITY", ---利姆鲁-魔王之路独有技能解锁
    CDC_RIMURU_RESIST = "CDC_RIMURU_RESIST", ---利姆鲁-魔王之路抗性
    CDC_RIMURUSTONE_BIND = "CDC_RIMURUSTONE_BIND", ---利姆鲁-石头绑定
    CDC_RIMURUSTONE_UNBIND = "CDC_RIMURUSTONE_UNBIND", ---利姆鲁-石头解除绑定
    CDC_RIMURUSTONE_BREAK = "CDC_RIMURUSTONE_BREAK", ---利姆鲁-石头分解
    CDC_RIMURUSTONE_CHECK = "CDC_RIMURUSTONE_CHECK", ---利姆鲁-石头查看
    CDC_CORRIDOR_SWAP = "CDC_CORRIDOR_SWAP", ---魂之回廊交换

    ------ 图鉴系统 ------
    CDC_ALBUM_ACTIVE = "CDC_ALBUM_ACTIVE", --图鉴激活
    CDC_ALBUM_EVOLVE = "CDC_ALBUM_EVOLVE", --图鉴进化
    
    ---- 活动 -----
    ACTIVITY_HEROSIGN = "ACTIVITY_HEROSIGN", --活动 英雄降临


    ----- 联盟系统 ------
    CDC_LEAGUE_JOIN = "CDC_LEAGUE_JOIN", --加入联盟
    CDC_LEAGUE_EXIT = "CDC_LEAGUE_EXIT", --退出联盟
    CDC_LEAGUE_LIST = "CDC_LEAGUE_LIST", --联盟列表
    CDC_LEAGUE_UPDATE_EXP = "CDC_LEAGUE_UPDATE_EXP", --联盟经验刷新
    CDC_LEAGUE_UPDATE_LEVEL = "CDC_LEAGUE_UPDATE_LEVEL", --联盟升级
    CDC_LEAGUE_UPDATE_TREASURE_RULE = "CDC_LEAGUE_UPDATE_TREASURE_RULE", --联盟自定义宝藏规则
    CDC_LEAGUE_UPDATE_FLAG = "CDC_LEAGUE_UPDATE_FLAG", --联盟自定义旗帜
    CDC_LEAGUE_UPDATE_NAME = "CDC_LEAGUE_UPDATE_NAME", --联盟自定义名称
    CDC_LEAGUE_UPDATE_NOTICE = "CDC_LEAGUE_UPDATE_NOTICE", --联盟自定义公告
    CDC_LEAGUE_UPDATE_LEADER = "CDC_LEAGUE_UPDATE_LEADER", --联盟转让
    CDC_LEAGUE_UPDATE_MEMBER = "CDC_LEAGUE_UPDATE_MEMBER", --联盟成员刷新
    CDC_LEAGUE_UPDATE_TASK = "CDC_LEAGUE_UPDATE_TASK", --联盟任务刷新
    CDC_LEAGUE_UPDATE_CHALLENGE = "CDC_LEAGUE_UPDATE_CHALLENGE", --联盟挑战刷新
    CDC_LEAGUE_UPDATE_DISCOUNT = "CDC_LEAGUE_UPDATE_DISCOUNT", --联盟折扣刷新
    CDC_LEAGUE_UPDATE_DISCOUNT_TICKET = "CDC_LEAGUE_UPDATE_DISCOUNT_TICKET", --我自己的联盟打折券数量刷新
    CDC_LEAGUE_BUY_GOODS = "CDC_LEAGUE_BUY_GOODS", --联盟商店购买商品
    CDC_LEAGUE_UPDATE_DAILY = "CDC_LEAGUE_UPDATE_DAILY", --联盟签到状态更新

    --尚未使用的事件
    CDC_LEAGUE_APPLY = "CDC_LEAGUE_APPLY", --联盟申请刷新
    CDC_LEAGUE_LOG = "CDC_LEAGUE_LOG", --联盟日志刷新
    CDC_LEAGUE_CUSTOM_DUTY = "CDC_LEAGUE_CUSTOM_DUTY", --联盟自定义职位

    --CDC_LEAGUE_SEND_MAIL = "CDC_LEAGUE_SEND_MAIL", --联盟发送邮件
    --CDC_LEAGUE_CUSTOM_MAIL = "CDC_LEAGUE_CUSTOM_MAIL", --联盟自定义邮件
    --CDC_LEAGUE_CUSTOM_BROADCAST = "CDC_LEAGUE_CUSTOM_BROADCAST", --联盟自定义广播

    ----- 数据刷新 ------
    CDC_ITEM_REFRESH = "CDC_ITEM_REFRESH", --物品刷新
    CDC_EQUIP_REFRESH = "CDC_EQUIP_REFRESH", --装备刷新

}

-- 数字键值(快速访问 避免重复)
-- BattleConst.MATRIX 和此id可能冲突 编号调整从501起
local index = 501;
for k, _ in pairs(EventConst) do
    EventConst[k] = index
    index = index + 1
end

return EventConst
