---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kojin.
--- DateTime: 2024/7/1 下午6:44
---
local DebugConst = require("Core/Debug/DebugConst")
local DebugHelper = DebugHelper
local DebugModule = {}

--入口中文描述
DebugModule.ENTRY_NAME = "养成GM"
function DebugModule.getLevel(sender, menu, value)
    --DebugHelper.OpenDebugLogUI()
    SendHandlers.ReqGmcmd("getAllLevel:" .. value)
end

function DebugModule.getEquip(sender, menu, value)
    SendHandlers.ReqGmcmd("getAllEquip:" .. value)
    --DebugHelper.OpenDebugLogUI()
end

function DebugModule.getCombo(sender, menu, value)
    SendHandlers.ReqGmcmd("getAllCombo:" .. value)
    --DebugHelper.OpenDebugLogUI()
end

function DebugModule.clearEquip(sender, menu)
    --DebugHelper.OpenDebugLogUI()
    SendHandlers.ReqGmcmd("clearEquip")

end
function DebugModule.clearDragon(sender, menu)
    SendHandlers.ReqGmcmd("clearDragon")
    --DebugHelper.OpenDebugLogUI()
end

function DebugModule.clearHero(sender, menu)
    SendHandlers.ReqGmcmd("clearHero")
    --DebugHelper.OpenDebugLogUI()
end

function DebugModule.clearAll(sender, menu)
    --DebugHelper.OpenDebugLogUI()
    SendHandlers.ReqGmcmd("clearAll")

end
--功能列表
DebugModule.FUNC_MENU = {
    { name = "一键升级", typ = DebugConst.BTN_TYPE_INPUT, func = DebugModule.getLevel },
    { name = "一键获得装备", typ = DebugConst.BTN_TYPE_INPUT, func = DebugModule.getEquip },
    { name = "组合命令", typ = DebugConst.BTN_TYPE_INPUT, func = DebugModule.getCombo },
    { name = "一键清空装备", typ = DebugConst.BTN_TYPE_BUTTON, func = DebugModule.clearEquip },
    { name = "一键清空英雄", typ = DebugConst.BTN_TYPE_BUTTON, func = DebugModule.clearHero },
    { name = "一键清空全部", typ = DebugConst.BTN_TYPE_BUTTON, func = DebugModule.clearAll },
}

return DebugModule