---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kojin.
--- DateTime: 2024/7/3 下午3:02
---
local DebugConst = require("Core/Debug/DebugConst")
local DebugHelper = DebugHelper
local DebugModule = {}
DebugModule.ENTRY_NAME = "战斗系统"

function DebugModule.SkipYuye(sender, menu, value)
    -- main关卡进度
    DebugModule.reqNamedGM('skipNightmareLevel:',value)
end

function DebugModule.SkipTrail(sender, menu, value)
    -- main关卡进度
    DebugModule.reqNamedGM('skipTrialLevel:',value)
end

function DebugModule.setWorldBossLevel(sender, menu, value)
    -- main关卡进度
    DebugModule.reqNamedGM('endlessWarLevel:',value)
end

function DebugModule.setWorldBossTime(sender, menu, value)
    -- main关卡进度
    DebugModule.reqNamedGM('endlessWarChallenge:',value)
end

function DebugModule.odsAddRelic(sender, menu, value)
    DebugModule.reqNamedGM("odsAddRelic:",value)
end

function DebugModule.odsDeleteRelic(sender, menu, value)
    DebugModule.reqNamedGM("odsDeleteRelic:",value)
end

function DebugModule.resetOds(sender, menu, value)
    DebugModule.reqNamedGM("resetOds:",value)
end

function DebugModule.intoNextLayer(sender, menu, value)
    DebugModule.reqNamedGM("intoNextLayer:",value)
end

function DebugModule.intoNextLayer(sender, menu, value)
    DebugModule.reqNamedGM("intoNextLayer:",value)
end

function DebugModule.qmzy(sender, menu, value)
    SendHandlers.ReqGmcmd("qmzy2:"..value)
end

function DebugModule.zyst(sender, menu, value)
    SendHandlers.ReqGmcmd("zyst2:"..value)
end
function DebugModule.ymht(sender, menu, value)
    SendHandlers.ReqGmcmd("ymht2:"..value)
end


DebugModule.FUNC_MENU = {
    { name = "绝望梦魇（层）", typ = DebugConst.BTN_TYPE_INPUT, func = DebugModule.SkipYuye },
    { name = "试炼之境（关：层）", typ = DebugConst.BTN_TYPE_INPUT, func = DebugModule.SkipTrail },
    { name = "世界boss（等级）", typ = DebugConst.BTN_TYPE_INPUT, func = DebugModule.setWorldBossLevel },
    { name = "世界boss（次数）", typ = DebugConst.BTN_TYPE_INPUT, func = DebugModule.setWorldBossTime },
    { name = "深海(龙眠)添加圣物", typ = DebugConst.BTN_TYPE_INPUT, func = DebugModule.odsAddRelic},
    { name = "深海(龙眠)删除圣物", typ = DebugConst.BTN_TYPE_INPUT, func = DebugModule.odsDeleteRelic},
    { name = "复活所有阵亡英雄", typ = DebugConst.BTN_TYPE_INPUT, func = DebugModule.resuscitateAllHero},
    { name = "强制重置当前奥德赛难度", typ = DebugConst.BTN_TYPE_INPUT, func = DebugModule.resetOds},
    { name = "深海(龙眠)跳关", typ = DebugConst.BTN_TYPE_INPUT, func = DebugModule.intoNextLayer},
    { name = "囚魔之狱", typ = DebugConst.BTN_TYPE_INPUT, func = DebugModule.qmzy},
    { name = "阵营圣塔", typ = DebugConst.BTN_TYPE_INPUT, func = DebugModule.zyst},
    { name = "湮灭幻塔", typ = DebugConst.BTN_TYPE_INPUT, func = DebugModule.ymht},
}

return DebugModule