local Data = {
	[100010001] = {
		["CueID"] = 100010001,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "H001_battle_attack_basic_01_behit",
			["SourcePath"] = "Effects/Heros/10001/H001_battle_attack_basic_01_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "0",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[100010002] = {
		["CueID"] = 100010002,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "H001_battle_attack_basic_02_behit",
			["SourcePath"] = "Effects/Heros/10001/H001_battle_attack_basic_02_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[100010003] = {
		["CueID"] = 100010003,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_10001_battle_attack_ultra_01_1",
			["SourcePath"] = "Effects/Heros/10001/efx_10001_battle_attack_ultra_01_1.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 2,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[100010004] = {
		["CueID"] = 100010004,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["SourcePath"] = "",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[100015001] = {
		["CueID"] = 100015001,
		["CueType"] = 5,
		["TypeString"] = "PostProcess",
		["PostProcess"]= {
			["type"] = 6,
			["depthParam"]= {
				["focusDistance"] = 10,
				["aperture"] = 5.6,
				["focalLength"] = 50,
				["blurSize"] = 0,
			},
			["fadeIn"] = 0.3,
			["fadeOut"] = 0.3,
			["length"] = 3.7,
			["cullingPlayer"] = 1,
		},
	},
	[100015002] = {
		["CueID"] = 100015002,
		["CueType"] = 5,
		["TypeString"] = "PostProcess",
		["PostProcess"]= {
			["type"] = 4,
			["tintColorParam"]= {
				["R"] = 1,
				["G"] = 1,
				["B"] = 1,
				["A"] = 1,
				["blendMode"] = false,
			},
			["fadeIn"] = 0.5,
			["fadeOut"] = 0.5,
			["length"] = 1.5,
		},
	},
	[100010005] = {
		["CueID"] = 100010005,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["SourcePath"] = "",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bone_Weapon_01/Bip001 Weapon",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 1,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[100018001] = {
		["CueID"] = 100018001,
		["CueType"] = 8,
		["TypeString"] = "SequenceFrame",
		["SequenceFrame"]= {
			["SequenceType"] = 0,
			["SequenceName"] = "110001",
			["FrameCount"] = 31,
		},
	},
	[100015003] = {
		["CueID"] = 100015003,
		["CueType"] = 5,
		["TypeString"] = "PostProcess",
		["PostProcess"]= {
			["type"] = 6,
			["depthParam"]= {
				["focusDistance"] = 7,
				["aperture"] = 0.1,
				["focalLength"] = 300,
				["blurSize"] = 3,
			},
			["length"] = 3.9,
			["cullingPlayer"] = 1,
		},
	},
	[100015004] = {
		["CueID"] = 100015004,
		["CueType"] = 5,
		["TypeString"] = "PostProcess",
		["PostProcess"]= {
			["type"] = 7,
			["motionBlurParam"]= {
				["blurSize"] = 1,
			},
			["length"] = 7,
		},
	},
	[100013001] = {
		["CueID"] = 100013001,
		["CueType"] = 3,
		["TypeString"] = "CueShake",
		["CueShake"]= {
			["Source"] = "ScreenShake",
		},
	},
	[100013002] = {
		["CueID"] = 100013002,
		["CueType"] = 3,
		["TypeString"] = "CueShake",
		["CueShake"]= {
			["Source"] = "ScreenShake2",
		},
	},
	[100016001] = {
		["CueID"] = 100016001,
		["CueType"] = 6,
		["TypeString"] = "ModelEffect",
		["ModelEffect"]= {
			["type"] = 4,
			["modelChangeAll"]= {
				["commonModelId"] = 1120101,
				["animator"] = "Animators/Hero/Hero_11201_01.controller",
			},
			["fadeIn"] = 0.2,
			["length"] = -1,
			["howToPlay"] = 3,
		},
	},
	[100019001] = {
		["CueID"] = 100019001,
		["CueType"] = 9,
		["TypeString"] = "TargetCamera",
		["TargetCamera"]= {
			["SourcePath"] = "Camera/CameraCurvy/Heroes/11004/cam_11004_battle_ultra.anim",
			["FadeIn"] = 0.2,
			["Length"] = 2,
			["FadeOut"] = 0.2,
		},
	},
	[100011001] = {
		["CueID"] = 100011001,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_11004_51_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_11004_51_1.ogg",
		},
	},
	[100011002] = {
		["CueID"] = 100011002,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_11004_51_2",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_11004_51_2.ogg",
		},
	},
	[100010006] = {
		["CueID"] = 100010006,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["SourcePath"] = "",
			["howToPlay"] = 0,
			["playLength"] = 0,
			["loopTimes"] = 0,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[100011003] = {
		["CueID"] = 100011003,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_11004_21_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_11004_21_1.ogg",
		},
	},
	[100011004] = {
		["CueID"] = 100011004,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_11004_11_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_11004_11_1.ogg",
		},
	},
	[100011005] = {
		["CueID"] = 100011005,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_11004_11_2",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_11004_11_2.ogg",
		},
	},
	[100010007] = {
		["CueID"] = 100010007,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_11004_battle_new_1",
			["SourcePath"] = "Effects/Heros/11004/efx_11004_battle_new_1.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
}
return Data
