local Data = {
	[120070001] = {
		["CueID"] = 120070001,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12007_battle_attack_basic_01_1",
			["SourcePath"] = "Effects/Heros/12007/efx_12007_battle_attack_basic_01_1.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120070002] = {
		["CueID"] = 120070002,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12007_battle_attack_basic_01_2",
			["SourcePath"] = "Effects/Heros/12007/efx_12007_battle_attack_basic_01_2.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120070003] = {
		["CueID"] = 120070003,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12007_battle_attack_basic_01_behit",
			["SourcePath"] = "Effects/Heros/12007/efx_12007_battle_attack_basic_01_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120070004] = {
		["CueID"] = 120070004,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12007_battle_attack_passive_21",
			["SourcePath"] = "Effects/Heros/12007/efx_12007_battle_attack_passive_21.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120070005] = {
		["CueID"] = 120070005,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12007_battle_attack_passive_behit",
			["SourcePath"] = "Effects/Heros/12007/efx_12007_battle_attack_passive_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120070006] = {
		["CueID"] = 120070006,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12007_battle_attack_ultra_61_1",
			["SourcePath"] = "Effects/Heros/12007/efx_12007_battle_attack_ultra_61_1.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120070007] = {
		["CueID"] = 120070007,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12007_battle_attack_ultra_61_2",
			["SourcePath"] = "Effects/Heros/12007/efx_12007_battle_attack_ultra_61_2.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120070008] = {
		["CueID"] = 120070008,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12007_battle_attack_ultra_61_behit",
			["SourcePath"] = "Effects/Heros/12007/efx_12007_battle_attack_ultra_61_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120078001] = {
		["CueID"] = 120078001,
		["CueType"] = 8,
		["TypeString"] = "SequenceFrame",
		["SequenceFrame"]= {
			["SequenceType"] = 2,
			["SequenceName"] = "HeroUltra/12007/video_12007_ultra_short.mp4",
			["FrameCount"] = 0,
		},
	},
	[120075001] = {
		["CueID"] = 120075001,
		["CueType"] = 5,
		["TypeString"] = "PostProcess",
		["PostProcess"]= {
			["type"] = 4,
			["tintColorParam"]= {
				["R"] = 0,
				["G"] = 0,
				["B"] = 0,
				["A"] = 255,
				["blendMode"] = false,
			},
			["fadeOut"] = 0.2,
			["length"] = 1.5,
			["cullingPlayer"] = 1,
		},
	},
	[120073001] = {
		["CueID"] = 120073001,
		["CueType"] = 3,
		["TypeString"] = "CueShake",
		["CueShake"]= {
			["Source"] = "AxeScreenShake04",
		},
	},
	[120070009] = {
		["CueID"] = 120070009,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12007_battle_attack_ultra_61_1_HUD",
			["SourcePath"] = "Effects/Heros/12007/efx_12007_battle_attack_ultra_61_1_HUD.prefab",
			["howToPlay"] = 0,
			["playLength"] = 1.5,
			["loopTimes"] = 0,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 3,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120071001] = {
		["CueID"] = 120071001,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_12007_51_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_12007_51_1.ogg",
		},
	},
	[120071002] = {
		["CueID"] = 120071002,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_12007_61_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_12007_61_1.ogg",
		},
	},
	[120071003] = {
		["CueID"] = 120071003,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_12007_11_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_12007_11_1.ogg",
		},
	},
	[120071004] = {
		["CueID"] = 120071004,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_12007_12_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_12007_12_1.ogg",
		},
	},
	[120071005] = {
		["CueID"] = 120071005,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_12007_21_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_12007_21_1.ogg",
		},
	},
	[120076001] = {
		["CueID"] = 120076001,
		["CueType"] = 6,
		["TypeString"] = "ModelEffect",
		["ModelEffect"]= {
			["type"] = 3,
			["modelChangeMotion"]= {
				["oldStateName"] = "idle",
				["newStateName"] = "idle02",
			},
			["length"] = -1,
			["howToPlay"] = 2,
		},
	},
}
return Data
