local Data = {
	[120046001] = {
		["CueID"] = 120046001,
		["CueType"] = 6,
		["TypeString"] = "ModelEffect",
		["ModelEffect"]= {
			["type"] = 4,
			["modelChangeAll"]= {
				["commonModelId"] = 12004010,
				["animator"] = "Animators/Hero/Hero_12004_01.controller",
			},
			["fadeIn"] = 0.2,
			["length"] = -1,
			["howToPlay"] = 3,
		},
	},
	[120040001] = {
		["CueID"] = 120040001,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12004_battle_attack_basic_01",
			["SourcePath"] = "Effects/Heros/12004/efx_12004_battle_attack_basic_01.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120040002] = {
		["CueID"] = 120040002,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12004_battle_attack_basic_02",
			["SourcePath"] = "Effects/Heros/12004/efx_12004_battle_attack_basic_02.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120040003] = {
		["CueID"] = 120040003,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12004_battle_attack_basic_01_behit",
			["SourcePath"] = "Effects/Heros/12004/efx_12004_battle_attack_basic_01_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120040004] = {
		["CueID"] = 120040004,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12004_battle_attack_passive_21_1",
			["SourcePath"] = "Effects/Heros/12004/efx_12004_battle_attack_passive_21_1.prefab",
			["howToPlay"] = 0,
			["playLength"] = 1.5,
			["loopTimes"] = 1,
			["mount"] = "12004_body_01",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120040005] = {
		["CueID"] = 120040005,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12004_battle_attack_passive_21_2",
			["SourcePath"] = "Effects/Heros/12004/efx_12004_battle_attack_passive_21_2.prefab",
			["howToPlay"] = 1,
			["playLength"] = 1.5,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=7.5, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120040006] = {
		["CueID"] = 120040006,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12004_battle_attack_passive_21_behit",
			["SourcePath"] = "Effects/Heros/12004/efx_12004_battle_attack_passive_21_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120040007] = {
		["CueID"] = 120040007,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_1200402_battle_attack_basic_01",
			["SourcePath"] = "Effects/Heros/1200402/efx_1200402_battle_attack_basic_01.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120040008] = {
		["CueID"] = 120040008,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_1200402_battle_attack_basic_02",
			["SourcePath"] = "Effects/Heros/1200402/efx_1200402_battle_attack_basic_02.prefab",
			["howToPlay"] = 1,
			["playLength"] = -1,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120040009] = {
		["CueID"] = 120040009,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_1200402_battle_attack_basic_03",
			["SourcePath"] = "Effects/Heros/1200402/efx_1200402_battle_attack_basic_03.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "Bip001 R Hand",
			["endPos"] = "Bip001 Spine",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120040010] = {
		["CueID"] = 120040010,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_1200402_battle_attack_basic_01_behit",
			["SourcePath"] = "Effects/Heros/1200402/efx_1200402_battle_attack_basic_01_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120048001] = {
		["CueID"] = 120048001,
		["CueType"] = 8,
		["TypeString"] = "SequenceFrame",
		["SequenceFrame"]= {
			["SequenceType"] = 2,
			["SequenceName"] = "HeroUltra/12004/video_12004_ultra.mp4",
			["FrameCount"] = 0,
		},
	},
	[120048002] = {
		["CueID"] = 120048002,
		["CueType"] = 8,
		["TypeString"] = "SequenceFrame",
		["SequenceFrame"]= {
			["SequenceType"] = 2,
			["SequenceName"] = "HeroUltra/12004/video_12004_ultra_short.mp4",
			["FrameCount"] = 0,
		},
	},
	[120040011] = {
		["CueID"] = 120040011,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12004_battle_attack_passive_21_2",
			["SourcePath"] = "Effects/Heros/12004/efx_12004_battle_attack_passive_21_2.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 1,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0.5,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120041001] = {
		["CueID"] = 120041001,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_12004_51_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_12004_51_1.ogg",
		},
	},
	[120041002] = {
		["CueID"] = 120041002,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_12004_11_3",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_12004_11_3.ogg",
		},
	},
	[120040012] = {
		["CueID"] = 120040012,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["SourcePath"] = "",
			["howToPlay"] = 0,
			["playLength"] = 2,
			["loopTimes"] = 0,
			["mount"] = "",
			["mountType"] = 3,
			["offset"] ={["x"]=0.5, ["y"]=0, ["z"]=0.3, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120040013] = {
		["CueID"] = 120040013,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12004_battle_new_2",
			["SourcePath"] = "Effects/Heros/12004/efx_12004_battle_new_2.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120041003] = {
		["CueID"] = 120041003,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_12004_61_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_12004_61_1.ogg",
		},
	},
	[120040014] = {
		["CueID"] = 120040014,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12004_battle_attack_ultra_61_1_HUD",
			["SourcePath"] = "Effects/Heros/1200402/efx_12004_battle_attack_ultra_61_1_HUD.prefab",
			["howToPlay"] = 0,
			["playLength"] = 2,
			["loopTimes"] = 0,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 3,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120045001] = {
		["CueID"] = 120045001,
		["CueType"] = 5,
		["TypeString"] = "PostProcess",
		["PostProcess"]= {
			["type"] = 4,
			["tintColorParam"]= {
				["R"] = 0,
				["G"] = 0,
				["B"] = 0,
				["A"] = 0.8784314,
				["blendMode"] = true,
			},
			["fadeIn"] = 0.1,
			["fadeOut"] = 0.2,
			["length"] = 2,
			["cullingPlayer"] = 1,
		},
	},
	[120040015] = {
		["CueID"] = 120040015,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12004_battle_attack_passive_22",
			["SourcePath"] = "Effects/Heros/12004/efx_12004_battle_attack_passive_22.prefab",
			["howToPlay"] = 1,
			["playLength"] = -1,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120040016] = {
		["CueID"] = 120040016,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12004_battle_attack_ultra_01_new",
			["SourcePath"] = "Effects/Heros/12004/efx_12004_battle_attack_ultra_01_new.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120040017] = {
		["CueID"] = 120040017,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12004_battle_attack_ultra_02_new",
			["SourcePath"] = "Effects/Heros/12004/efx_12004_battle_attack_ultra_02_new.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120040018] = {
		["CueID"] = 120040018,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12004_battle_attack_ultra_03_new",
			["SourcePath"] = "Effects/Heros/12004/efx_12004_battle_attack_ultra_03_new.prefab",
			["howToPlay"] = 0,
			["playLength"] = 0,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Spine",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120040019] = {
		["CueID"] = 120040019,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12004_battle_attack_passive_22_01",
			["SourcePath"] = "Effects/Heros/12004/efx_12004_battle_attack_passive_22_01.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 1,
			["mount"] = "Bip001 R Hand",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[120042001] = {
		["CueID"] = 120042001,
		["CueType"] = 2,
		["TypeString"] = "GroupCue",
		["GroupCue"]= {
			["CueList"] = {120040015,120040019,},
		},
	},
}
return Data
