local Data = {
	[130080001] = {
		["CueID"] = 130080001,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14008_battle_attack_basic_Hit",
			["SourcePath"] = "Effects/Heros/14008/efx_14008_battle_attack_basic_Hit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080002] = {
		["CueID"] = 130080002,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14008_battle_attack_basic_Ballistic",
			["SourcePath"] = "Effects/Heros/14008/efx_14008_battle_attack_basic_Ballistic.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "Bone016",
			["endPos"] = "Bip001 Spine",
			["height"] = 3,
			["curve"] = 5,
			["oppositeDirection"] = false,
		},
	},
	[130086001] = {
		["CueID"] = 130086001,
		["CueType"] = 6,
		["TypeString"] = "ModelEffect",
		["ModelEffect"]= {
			["type"] = 3,
			["modelChangeMotion"]= {
				["oldStateName"] = "idle",
				["newStateName"] = "idle01",
			},
			["length"] = 10,
			["howToPlay"] = 0,
		},
	},
	[130080003] = {
		["CueID"] = 130080003,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13008_battle_attack_passive_21_buff",
			["SourcePath"] = "Effects/Heros/13008/efx_13008_battle_attack_passive_21_buff.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Spine",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080004] = {
		["CueID"] = 130080004,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13008_battle_attack_basic_Hit02",
			["SourcePath"] = "Effects/Heros/13008/efx_13008_battle_attack_basic_Hit02.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080005] = {
		["CueID"] = 130080005,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13008_battle_attack_basic_Bullet02",
			["SourcePath"] = "Effects/Heros/13008/efx_13008_battle_attack_basic_Bullet02.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "Bone016",
			["endPos"] = "Bip001 Spine",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130082001] = {
		["CueID"] = 130082001,
		["CueType"] = 2,
		["TypeString"] = "GroupCue",
		["GroupCue"]= {
			["CueList"] = {130086001,130080003,},
		},
	},
	[130085001] = {
		["CueID"] = 130085001,
		["CueType"] = 5,
		["TypeString"] = "PostProcess",
		["PostProcess"]= {
			["type"] = 4,
			["tintColorParam"]= {
				["R"] = 0,
				["G"] = 0,
				["B"] = 0,
				["A"] = 0.9607843,
				["blendMode"] = true,
			},
			["fadeIn"] = 0.2,
			["fadeOut"] = 0.2,
			["length"] = 1.7,
			["cullingPlayer"] = 1,
		},
	},
	[130080006] = {
		["CueID"] = 130080006,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14003_battle_attack_ultra_01",
			["SourcePath"] = "Effects/Heros/14003/efx_14003_battle_attack_ultra_01.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Spine",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080007] = {
		["CueID"] = 130080007,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13008_battle_attack_passive_01",
			["SourcePath"] = "Effects/Heros/13008/efx_13008_battle_attack_passive_01.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080008] = {
		["CueID"] = 130080008,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13010_battle_attack_basic_01_bullet",
			["SourcePath"] = "Effects/Heros/13010/efx_13010_battle_attack_basic_01_bullet.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "Bone016",
			["endPos"] = "Bip001 Spine",
			["height"] = 3,
			["curve"] = 5,
			["oppositeDirection"] = false,
		},
	},
	[130080009] = {
		["CueID"] = 130080009,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13010_battle_attack_basic_01_bullet_behit",
			["SourcePath"] = "Effects/Heros/13010/efx_13010_battle_attack_basic_01_bullet_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080010] = {
		["CueID"] = 130080010,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14001_battle_attack_basic_01_bullet",
			["SourcePath"] = "Effects/Heros/14001/efx_14001_battle_attack_basic_01_bullet.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "Bone016",
			["endPos"] = "Bip001 Spine",
			["height"] = 3,
			["curve"] = 5,
			["oppositeDirection"] = false,
		},
	},
	[130080011] = {
		["CueID"] = 130080011,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14001_battle_attack_basic_01_bullet_behit",
			["SourcePath"] = "Effects/Heros/14001/efx_14001_battle_attack_basic_01_bullet_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080012] = {
		["CueID"] = 130080012,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13010_battle_attack_passive_21_buff",
			["SourcePath"] = "Effects/Heros/13010/efx_13010_battle_attack_passive_21_buff.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Spine",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080013] = {
		["CueID"] = 130080013,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14001_battle_attack_passive_01",
			["SourcePath"] = "Effects/Heros/14001/efx_14001_battle_attack_passive_01.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080014] = {
		["CueID"] = 130080014,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14001_battle_attack_ultra_01_bullet",
			["SourcePath"] = "Effects/Heros/14001/efx_14001_battle_attack_ultra_01_bullet.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "Bone016",
			["endPos"] = "Bip001 Spine",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080015] = {
		["CueID"] = 130080015,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14001_battle_attack_ultra_01_bullet_behit",
			["SourcePath"] = "Effects/Heros/14001/efx_14001_battle_attack_ultra_01_bullet_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080016] = {
		["CueID"] = 130080016,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14009_battle_attack_basic_01_bullet",
			["SourcePath"] = "Effects/Heros/14009/efx_14009_battle_attack_basic_01_bullet.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "Bone016",
			["endPos"] = "Bip001 Spine",
			["height"] = 3,
			["curve"] = 5,
			["oppositeDirection"] = false,
		},
	},
	[130080017] = {
		["CueID"] = 130080017,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14009_battle_attack_basic_01_bullet_behit",
			["SourcePath"] = "Effects/Heros/14009/efx_14009_battle_attack_basic_01_bullet_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080018] = {
		["CueID"] = 130080018,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14009_battle_attack_passive_01",
			["SourcePath"] = "Effects/Heros/14009/efx_14009_battle_attack_passive_01.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bone016",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080019] = {
		["CueID"] = 130080019,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14009_battle_attack_passive_01_behit",
			["SourcePath"] = "Effects/Heros/14009/efx_14009_battle_attack_passive_01_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080020] = {
		["CueID"] = 130080020,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14009_battle_attack_ultra_01_bullet",
			["SourcePath"] = "Effects/Heros/14009/efx_14009_battle_attack_ultra_01_bullet.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "Bone016",
			["endPos"] = "Bip001 Spine",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080021] = {
		["CueID"] = 130080021,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14009_battle_attack_ultra_01_bullet_behit",
			["SourcePath"] = "Effects/Heros/14009/efx_14009_battle_attack_ultra_01_bullet_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080022] = {
		["CueID"] = 130080022,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14001_battle_attack_ultra_01",
			["SourcePath"] = "Effects/Heros/14001/efx_14001_battle_attack_ultra_01.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bone016",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080023] = {
		["CueID"] = 130080023,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14009_battle_attack_ultra_01",
			["SourcePath"] = "Effects/Heros/14009/efx_14009_battle_attack_ultra_01.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bone016",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080024] = {
		["CueID"] = 130080024,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13008_test_double_side",
			["SourcePath"] = "Effects/Heros/13008/efx_13008_test_double_side.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 2,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130081001] = {
		["CueID"] = 130081001,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_13008_11_2",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_13008_11_2.ogg",
		},
	},
	[130081002] = {
		["CueID"] = 130081002,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_13008_12_2",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_13008_12_2.ogg",
		},
	},
	[130080025] = {
		["CueID"] = 130080025,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13008_battle_attack_basic_01_1",
			["SourcePath"] = "Effects/Heros/13008/efx_13008_battle_attack_basic_01_1.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080026] = {
		["CueID"] = 130080026,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13008_battle_attack_basic_01_2",
			["SourcePath"] = "Effects/Heros/13008/efx_13008_battle_attack_basic_01_2.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 1,
			["mount"] = "Bip001 R Hand",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "Bip001 R Hand",
			["endPos"] = "Bip001 Spine",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080027] = {
		["CueID"] = 130080027,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13008_battle_attack_basic_01_behit",
			["SourcePath"] = "Effects/Heros/13008/efx_13008_battle_attack_basic_01_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080028] = {
		["CueID"] = 130080028,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13008_battle_attack_basic_02_1",
			["SourcePath"] = "Effects/Heros/13008/efx_13008_battle_attack_basic_02_1.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080029] = {
		["CueID"] = 130080029,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13008_battle_attack_basic_02_1_hand",
			["SourcePath"] = "Effects/Heros/13008/efx_13008_battle_attack_basic_02_1_hand.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 R Hand",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080030] = {
		["CueID"] = 130080030,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13008_battle_attack_basic_02_2",
			["SourcePath"] = "Effects/Heros/13008/efx_13008_battle_attack_basic_02_2.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "Bip001 R Hand",
			["endPos"] = "Bip001 Spine",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080031] = {
		["CueID"] = 130080031,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13008_battle_attack_basic_02_behit",
			["SourcePath"] = "Effects/Heros/13008/efx_13008_battle_attack_basic_02_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080032] = {
		["CueID"] = 130080032,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13008_battle_attack_passive_21_buff",
			["SourcePath"] = "Effects/Heros/13008/efx_13008_battle_attack_passive_21_buff.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080033] = {
		["CueID"] = 130080033,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13008_battle_attack_ultra_51_1",
			["SourcePath"] = "Effects/Heros/13008/efx_13008_battle_attack_ultra_51_1.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130080034] = {
		["CueID"] = 130080034,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13008_battle_attack_ultra_51_buff",
			["SourcePath"] = "Effects/Heros/13008/efx_13008_battle_attack_ultra_51_buff.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Spine",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130081003] = {
		["CueID"] = 130081003,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_1300801_11_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_1300801_11_1.ogg",
		},
	},
	[130081004] = {
		["CueID"] = 130081004,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_1300801_11_2",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_1300801_11_2.ogg",
		},
	},
	[130081005] = {
		["CueID"] = 130081005,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_1300801_12_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_1300801_12_1.ogg",
		},
	},
	[130081006] = {
		["CueID"] = 130081006,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_1300801_12_2",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_1300801_12_2.ogg",
		},
	},
	[130081007] = {
		["CueID"] = 130081007,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_1300801_51_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_1300801_51_1.ogg",
		},
	},
	[130080035] = {
		["CueID"] = 130080035,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13008_battle_attack_basic_02_2",
			["SourcePath"] = "Effects/Heros/13008/efx_13008_battle_attack_basic_02_2.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 2,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "Bip001 R Hand",
			["endPos"] = "Bip001 Spine",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
}
return Data
