local Data = {
	[130130001] = {
		["CueID"] = 130130001,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13013_battle_attack_ultra_61_1",
			["SourcePath"] = "Effects/Heros/13013/efx_13013_battle_attack_ultra_61_1.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130130002] = {
		["CueID"] = 130130002,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "13013_acc",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130130003] = {
		["CueID"] = 130130003,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13013_battle_attack_ultra_61_3 ",
			["SourcePath"] = "Effects/Heros/13013/efx_13013_battle_attack_ultra_61_3 .prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 3,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130130004] = {
		["CueID"] = 130130004,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130130005] = {
		["CueID"] = 130130005,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130130006] = {
		["CueID"] = 130130006,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130130007] = {
		["CueID"] = 130130007,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130130008] = {
		["CueID"] = 130130008,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130130009] = {
		["CueID"] = 130130009,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13013_battle_attack_ultra_61_behit",
			["SourcePath"] = "Effects/Heros/13013/efx_13013_battle_attack_ultra_61_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130130010] = {
		["CueID"] = 130130010,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13013_battle_attack_Boost",
			["SourcePath"] = "Effects/Heros/13013/efx_13013_battle_attack_Boost.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130130011] = {
		["CueID"] = 130130011,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13013_battle_attack_basic_01_1",
			["SourcePath"] = "Effects/Heros/13013/efx_13013_battle_attack_basic_01_1.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130130012] = {
		["CueID"] = 130130012,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13013_battle_attack_basic_01_2",
			["SourcePath"] = "Effects/Heros/13013/efx_13013_battle_attack_basic_01_2.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "13013_acc",
			["endPos"] = "Bip001 Behit",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130130013] = {
		["CueID"] = 130130013,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13013_battle_attack_passive_21_1",
			["SourcePath"] = "Effects/Heros/13013/efx_13013_battle_attack_passive_21_1.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130130014] = {
		["CueID"] = 130130014,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13013_battle_attack_passive_21_2",
			["SourcePath"] = "Effects/Heros/13013/efx_13013_battle_attack_passive_21_2.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "13013_acc",
			["endPos"] = "Bip001 Behit",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130130015] = {
		["CueID"] = 130130015,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13013_battle_attack_passive_21_behit",
			["SourcePath"] = "Effects/Heros/13013/efx_13013_battle_attack_passive_21_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130130016] = {
		["CueID"] = 130130016,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13013_battle_attack_passive_21_debuff",
			["SourcePath"] = "Effects/Heros/13013/efx_13013_battle_attack_passive_21_debuff.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0.7,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130130017] = {
		["CueID"] = 130130017,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13013_battle_attack_passive_21_4",
			["SourcePath"] = "Effects/Heros/13013/efx_13013_battle_attack_passive_21_4.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130130018] = {
		["CueID"] = 130130018,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13013_battle_attack_ultra_61_HUD",
			["SourcePath"] = "Effects/Heros/13013/efx_13013_battle_attack_ultra_61_HUD.prefab",
			["howToPlay"] = 0,
			["playLength"] = 2.5,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 3,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[130135001] = {
		["CueID"] = 130135001,
		["CueType"] = 5,
		["TypeString"] = "PostProcess",
		["PostProcess"]= {
			["type"] = 4,
			["tintColorParam"]= {
				["R"] = 0,
				["G"] = 0,
				["B"] = 0,
				["A"] = 255,
				["blendMode"] = false,
			},
			["length"] = 2.5,
			["cullingPlayer"] = 1,
		},
	},
	[130136001] = {
		["CueID"] = 130136001,
		["CueType"] = 6,
		["TypeString"] = "ModelEffect",
		["ModelEffect"]= {
			["type"] = 1,
			["modelHide"]= {
				["hideHpLogo"] = true,
				["hideDamageNum"] = false,
				["skipHideModel"] = false,
			},
			["length"] = 1.7,
			["howToPlay"] = 0,
		},
	},
	[130138001] = {
		["CueID"] = 130138001,
		["CueType"] = 8,
		["TypeString"] = "SequenceFrame",
		["SequenceFrame"]= {
			["SequenceType"] = 2,
			["SequenceName"] = "HeroUltra/13013/video_13013_ultra_short.mp4",
			["FrameCount"] = 0,
		},
	},
	[130131001] = {
		["CueID"] = 130131001,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_13013_11_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_13013_11_1.ogg",
		},
	},
	[130131002] = {
		["CueID"] = 130131002,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_13013_11_2",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_13013_11_2.ogg",
		},
	},
	[130131003] = {
		["CueID"] = 130131003,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_13013_21_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_13013_21_1.ogg",
		},
	},
	[130131004] = {
		["CueID"] = 130131004,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_13013_51_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_13013_51_1.ogg",
		},
	},
	[130131005] = {
		["CueID"] = 130131005,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_13013_61_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_13013_61_1.ogg",
		},
	},
}
return Data
