local Data = {
	[150010001] = {
		["CueID"] = 150010001,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_15001_battle_attack_basic_behit",
			["SourcePath"] = "Effects/Heros/15001/efx_15001_battle_attack_basic_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[150018001] = {
		["CueID"] = 150018001,
		["CueType"] = 8,
		["TypeString"] = "SequenceFrame",
		["SequenceFrame"]= {
			["SequenceType"] = 2,
			["SequenceName"] = "HeroUltra/15001/video_15001_ultra.mp4",
			["FrameCount"] = 0,
		},
	},
	[150010002] = {
		["CueID"] = 150010002,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_15001_battle_attack_ultra_behit",
			["SourcePath"] = "Effects/Heros/15001/efx_15001_battle_attack_ultra_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[150010003] = {
		["CueID"] = 150010003,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_15001_battle_attack_ultra_pos",
			["SourcePath"] = "Effects/Heros/15001/efx_15001_battle_attack_ultra_pos.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 1,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[150010004] = {
		["CueID"] = 150010004,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_15001_battle_attack_passive_21_behit",
			["SourcePath"] = "Effects/Heros/15001/efx_15001_battle_attack_passive_21_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[150010005] = {
		["CueID"] = 150010005,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_15001_battle_attack_basic_01",
			["SourcePath"] = "Effects/Heros/15001/efx_15001_battle_attack_basic_01.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 L Hand",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[150010006] = {
		["CueID"] = 150010006,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_15001_battle_attack_basic_bullet",
			["SourcePath"] = "Effects/Heros/15001/efx_15001_battle_attack_basic_bullet.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "Bip001 L Hand",
			["endPos"] = "Bip001 Spine",
			["height"] = 2,
			["curve"] = 2,
			["oppositeDirection"] = false,
		},
	},
	[150018002] = {
		["CueID"] = 150018002,
		["CueType"] = 8,
		["TypeString"] = "SequenceFrame",
		["SequenceFrame"]= {
			["SequenceType"] = 2,
			["SequenceName"] = "HeroUltra/15001/video_15001_ultra_short.mp4",
			["FrameCount"] = 0,
		},
	},
	[150011001] = {
		["CueID"] = 150011001,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_15001_51_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_15001_51_1.ogg",
		},
	},
	[150011002] = {
		["CueID"] = 150011002,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_15001_51_2",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_15001_51_2.ogg",
		},
	},
	[150011003] = {
		["CueID"] = 150011003,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_15001_11_2",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_15001_11_2.ogg",
		},
	},
	[150011004] = {
		["CueID"] = 150011004,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_15001_12_2",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_15001_12_2.ogg",
		},
	},
	[150011005] = {
		["CueID"] = 150011005,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_15001_61_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_15001_61_1.ogg",
		},
	},
	[150010007] = {
		["CueID"] = 150010007,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_15001_battle_attack_ultra_61_1_HUD",
			["SourcePath"] = "Effects/Heros/15001/efx_15001_battle_attack_ultra_61_1_HUD.prefab",
			["howToPlay"] = 0,
			["playLength"] = 3.5,
			["loopTimes"] = 0,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 3,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[150015001] = {
		["CueID"] = 150015001,
		["CueType"] = 5,
		["TypeString"] = "PostProcess",
		["PostProcess"]= {
			["type"] = 4,
			["tintColorParam"]= {
				["R"] = 0,
				["G"] = 0,
				["B"] = 0,
				["A"] = 255,
				["blendMode"] = false,
			},
			["fadeOut"] = 0.2,
			["length"] = 2.5,
			["cullingPlayer"] = 1,
		},
	},
	[150010008] = {
		["CueID"] = 150010008,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_15001_battle_attack_passive_buff",
			["SourcePath"] = "Effects/Heros/15001/efx_15001_battle_attack_passive_buff.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Buff",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=-1.2, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[150010009] = {
		["CueID"] = 150010009,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_15001_battle_attack_passive_22",
			["SourcePath"] = "Effects/Heros/15001/efx_15001_battle_attack_passive_22.prefab",
			["howToPlay"] = 1,
			["playLength"] = -1,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Spine",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[150010010] = {
		["CueID"] = 150010010,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_15001_battle_attack_ultra_01_new",
			["SourcePath"] = "Effects/Heros/15001/efx_15001_battle_attack_ultra_01_new.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
}
return Data
