local Data = {
	[321040001] = {
		["CueID"] = 321040001,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "effect_1400101_battle_attack_basic_01",
			["SourcePath"] = "Effects/Heros/1400101/effect_1400101_battle_attack_basic_01.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[321040002] = {
		["CueID"] = 321040002,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "effect_1400101_battle_attack_basic_02",
			["SourcePath"] = "Effects/Heros/1400101/effect_1400101_battle_attack_basic_02.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[321040003] = {
		["CueID"] = 321040003,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "effect_1400101_battle_attack_basic_03",
			["SourcePath"] = "Effects/Heros/1400101/effect_1400101_battle_attack_basic_03.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "Bip001 L Hand",
			["endPos"] = "Bip001 Spine",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[321040004] = {
		["CueID"] = 321040004,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "effect_1400101_battle_attack_basic_03",
			["SourcePath"] = "Effects/Heros/1400101/effect_1400101_battle_attack_basic_03.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "Bip001 R Hand",
			["endPos"] = "Bip001 Spine",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[321040005] = {
		["CueID"] = 321040005,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "effect_1400101_battle_attack_basic_01_behit",
			["SourcePath"] = "Effects/Heros/1400101/effect_1400101_battle_attack_basic_01_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Spine",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[321040006] = {
		["CueID"] = 321040006,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "effect_1400101_battle_attack_passive_21_buff",
			["SourcePath"] = "Effects/Heros/1400101/effect_1400101_battle_attack_passive_21_buff.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[321040007] = {
		["CueID"] = 321040007,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "effect_1400101_battle_attack_ultra_51_1",
			["SourcePath"] = "Effects/Heros/1400101/effect_1400101_battle_attack_ultra_51_1.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[321040008] = {
		["CueID"] = 321040008,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "effect_1400101_battle_attack_ultra_51_3",
			["SourcePath"] = "Effects/Heros/1400101/effect_1400101_battle_attack_ultra_51_3.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[321040009] = {
		["CueID"] = 321040009,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "effect_1400101_battle_attack_ultra_51_2",
			["SourcePath"] = "Effects/Heros/1400101/effect_1400101_battle_attack_ultra_51_2.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Buff",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0.9, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[321040010] = {
		["CueID"] = 321040010,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "effect_1400101_battle_attack_basic_01_behit",
			["SourcePath"] = "Effects/Heros/1400101/effect_1400101_battle_attack_basic_01_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[321040011] = {
		["CueID"] = 321040011,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_3210401_battle_attack_basic_01_1",
			["SourcePath"] = "Effects/Heros/10401/efx_3210401_battle_attack_basic_01_1.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 L Hand",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[321040012] = {
		["CueID"] = 321040012,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_3210400_battle_attack_basic_01_2",
			["SourcePath"] = "Effects/Heros/10401/efx_3210400_battle_attack_basic_01_2.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 R Hand",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[321040013] = {
		["CueID"] = 321040013,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_3210400_battle_attack_basic_01_behit",
			["SourcePath"] = "Effects/Heros/10401/efx_3210400_battle_attack_basic_01_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[321040014] = {
		["CueID"] = 321040014,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_3210400_battle_attack_ultra_51_1",
			["SourcePath"] = "Effects/Heros/10401/efx_3210400_battle_attack_ultra_51_1.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[321040015] = {
		["CueID"] = 321040015,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_3210400_battle_attack_ultra_51_2",
			["SourcePath"] = "Effects/Heros/10401/efx_3210400_battle_attack_ultra_51_2.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 0,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[321040016] = {
		["CueID"] = 321040016,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_3210400_battle_attack_ultra_51_behit",
			["SourcePath"] = "Effects/Heros/10401/efx_3210400_battle_attack_ultra_51_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[321040017] = {
		["CueID"] = 321040017,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_3210401_battle_attack_ultra_52_2",
			["SourcePath"] = "Effects/Heros/10401/efx_3210401_battle_attack_ultra_52_2.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 L Hand",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[321040018] = {
		["CueID"] = 321040018,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_3210401_battle_attack_ultra_52_3",
			["SourcePath"] = "Effects/Heros/10401/efx_3210401_battle_attack_ultra_52_3.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 R Hand",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[321040019] = {
		["CueID"] = 321040019,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_3210401_battle_attack_ultra_52_1",
			["SourcePath"] = "Effects/Heros/10401/efx_3210401_battle_attack_ultra_52_1.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[321040020] = {
		["CueID"] = 321040020,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_3210401_battle_attack_ultra_52_behit",
			["SourcePath"] = "Effects/Heros/10401/efx_3210401_battle_attack_ultra_52_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[321040021] = {
		["CueID"] = 321040021,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_3210402_battle_attack_ultra_53_1",
			["SourcePath"] = "Effects/Heros/10401/efx_3210402_battle_attack_ultra_53_1.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[321040022] = {
		["CueID"] = 321040022,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_3210402_battle_attack_ultra_53_buff",
			["SourcePath"] = "Effects/Heros/10401/efx_3210402_battle_attack_ultra_53_buff.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[321041001] = {
		["CueID"] = 321041001,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_32104_11_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_32104_11_1.ogg",
		},
	},
	[321041002] = {
		["CueID"] = 321041002,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_32104_12_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_32104_12_1.ogg",
		},
	},
	[321041003] = {
		["CueID"] = 321041003,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_32104_51_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_32104_51_1.ogg",
		},
	},
	[321041004] = {
		["CueID"] = 321041004,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_32104_52_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_32104_52_1.ogg",
		},
	},
	[321041005] = {
		["CueID"] = 321041005,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_32104_53_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_32104_53_1.ogg",
		},
	},
}
return Data
