local Data = {
	[331030001] = {
		["CueID"] = 331030001,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_1400701_battle_attack_basic_01",
			["SourcePath"] = "Effects/Heros/1400701/efx_1400701_battle_attack_basic_01.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331030002] = {
		["CueID"] = 331030002,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_1400701_battle_attack_basic_02",
			["SourcePath"] = "Effects/Heros/1400701/efx_1400701_battle_attack_basic_02.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "Bip001 R Hand",
			["endPos"] = "Bip001 Spine",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331030003] = {
		["CueID"] = 331030003,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_1400701_battle_attack_basic_01_behit",
			["SourcePath"] = "Effects/Heros/1400701/efx_1400701_battle_attack_basic_01_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Spine",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331030004] = {
		["CueID"] = 331030004,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_1400701_battle_attack_ultra_51_1",
			["SourcePath"] = "Effects/Heros/1400701/efx_1400701_battle_attack_ultra_51_1.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331030005] = {
		["CueID"] = 331030005,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_1400701_battle_attack_ultra_51_2",
			["SourcePath"] = "Effects/Heros/1400701/efx_1400701_battle_attack_ultra_51_2.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "Bip001 R Hand",
			["endPos"] = "Bip001 Spine",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331030006] = {
		["CueID"] = 331030006,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_1400701_battle_attack_ultra_51_hehit",
			["SourcePath"] = "Effects/Heros/1400701/efx_1400701_battle_attack_ultra_51_hehit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331030007] = {
		["CueID"] = 331030007,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_1400701_battle_attack_ultra_51_buff",
			["SourcePath"] = "Effects/Heros/1400701/efx_1400701_battle_attack_ultra_51_buff.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
}
return Data
