local Data = {
	[331020001] = {
		["CueID"] = 331020001,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14007_battle_attack_basic_bullet",
			["SourcePath"] = "Effects/Heros/14007/efx_14007_battle_attack_basic_bullet.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "weapon_01",
			["endPos"] = "Bip001 Behit",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331020002] = {
		["CueID"] = 331020002,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14007_battle_attack_basic_01_behit",
			["SourcePath"] = "Effects/Heros/14007/efx_14007_battle_attack_basic_01_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331020003] = {
		["CueID"] = 331020003,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14007_battle_attack_basic_01",
			["SourcePath"] = "Effects/Heros/14007/efx_14007_battle_attack_basic_01.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "weapon_01",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331020004] = {
		["CueID"] = 331020004,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14007_battle_attack_passive_21_buff",
			["SourcePath"] = "Effects/Heros/14007/efx_14007_battle_attack_passive_21_buff.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "weapon_01",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331020005] = {
		["CueID"] = 331020005,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14007_battle_attack_passive_21_buff02",
			["SourcePath"] = "Effects/Heros/14007/efx_14007_battle_attack_passive_21_buff02.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331020006] = {
		["CueID"] = 331020006,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_buff_healup",
			["SourcePath"] = "Effects/Heros/Common/efx_common_buff_healup.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331020007] = {
		["CueID"] = 331020007,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_buff_Armor",
			["SourcePath"] = "Effects/Heros/Common/efx_common_buff_Armor.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331020008] = {
		["CueID"] = 331020008,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_buff_gainup",
			["SourcePath"] = "Effects/Heros/Common/efx_common_buff_gainup.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331020009] = {
		["CueID"] = 331020009,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14007_battle_attack_ultra_51_1_brown",
			["SourcePath"] = "Effects/Heros/14007/efx_14007_battle_attack_ultra_51_1_brown.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "weapon_01",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331020010] = {
		["CueID"] = 331020010,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14007_battle_attack_ultra_51_1_pink",
			["SourcePath"] = "Effects/Heros/14007/efx_14007_battle_attack_ultra_51_1_pink.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "weapon_01",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331020011] = {
		["CueID"] = 331020011,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14007_battle_attack_ultra_51_1_blue",
			["SourcePath"] = "Effects/Heros/14007/efx_14007_battle_attack_ultra_51_1_blue.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "weapon_01",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331020012] = {
		["CueID"] = 331020012,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14007_battle_attack_ultra_51_2_brown",
			["SourcePath"] = "Effects/Heros/14007/efx_14007_battle_attack_ultra_51_2_brown.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331020013] = {
		["CueID"] = 331020013,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14007_battle_attack_ultra_51_2_pink",
			["SourcePath"] = "Effects/Heros/14007/efx_14007_battle_attack_ultra_51_2_pink.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331020014] = {
		["CueID"] = 331020014,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14007_battle_attack_ultra_51_2_blue",
			["SourcePath"] = "Effects/Heros/14007/efx_14007_battle_attack_ultra_51_2_blue.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331020015] = {
		["CueID"] = 331020015,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14007_battle_attack_ultra_51_3",
			["SourcePath"] = "Effects/Heros/14007/efx_14007_battle_attack_ultra_51_3.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331020016] = {
		["CueID"] = 331020016,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14007_battle_attack_ultra_51_behit",
			["SourcePath"] = "Effects/Heros/14007/efx_14007_battle_attack_ultra_51_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "spine",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331020017] = {
		["CueID"] = 331020017,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_heal_behit",
			["SourcePath"] = "Effects/Heros/Common/efx_common_heal_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331025001] = {
		["CueID"] = 331025001,
		["CueType"] = 5,
		["TypeString"] = "PostProcess",
		["PostProcess"]= {
			["type"] = 4,
			["tintColorParam"]= {
				["R"] = 0,
				["G"] = 0,
				["B"] = 0,
				["A"] = 0.9607843,
				["blendMode"] = true,
			},
			["fadeIn"] = 0.25,
			["fadeOut"] = 0.25,
			["length"] = 1.5,
			["cullingPlayer"] = 1,
		},
	},
	[331021001] = {
		["CueID"] = 331021001,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_14007_11_2",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_14007_11_2.ogg",
		},
	},
	[331020018] = {
		["CueID"] = 331020018,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_1400701_battle_attack_basic_01",
			["SourcePath"] = "Effects/Heros/1400701/efx_1400701_battle_attack_basic_01.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331020019] = {
		["CueID"] = 331020019,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_1400701_battle_attack_basic_02",
			["SourcePath"] = "Effects/Heros/1400701/efx_1400701_battle_attack_basic_02.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "Bip001 R Hand",
			["endPos"] = "Bip001 Spine",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331020020] = {
		["CueID"] = 331020020,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_1400701_battle_attack_basic_01_behit",
			["SourcePath"] = "Effects/Heros/1400701/efx_1400701_battle_attack_basic_01_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Spine",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331020021] = {
		["CueID"] = 331020021,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_1400701_battle_attack_ultra_51_1",
			["SourcePath"] = "Effects/Heros/1400701/efx_1400701_battle_attack_ultra_51_1.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331020022] = {
		["CueID"] = 331020022,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_1400701_battle_attack_ultra_51_2",
			["SourcePath"] = "Effects/Heros/1400701/efx_1400701_battle_attack_ultra_51_2.prefab",
			["howToPlay"] = 1,
			["playLength"] = -1,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331020023] = {
		["CueID"] = 331020023,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_1400701_battle_attack_ultra_51_hehit",
			["SourcePath"] = "Effects/Heros/1400701/efx_1400701_battle_attack_ultra_51_hehit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 2,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331020024] = {
		["CueID"] = 331020024,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_1400701_battle_attack_ultra_51_buff",
			["SourcePath"] = "Effects/Heros/1400701/efx_1400701_battle_attack_ultra_51_buff.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "",
			["endPos"] = "",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[331021003] = {
		["CueID"] = 331021003,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_1400701_11_2",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_1400701_11_2.ogg",
		},
	},
	[331021004] = {
		["CueID"] = 331021004,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_1400701_51_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_1400701_51_1.ogg",
		},
	},
	[331021005] = {
		["CueID"] = 331021005,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "",
		},
	},
	[331021006] = {
		["CueID"] = 331021006,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_1400701_11_1",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_1400701_11_1.ogg",
		},
	},
}
return Data
