local Data = {
	[850010001] = {
		["CueID"] = 850010001,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "11001_battle_attack_passive_21_behit",
			["SourcePath"] = "Effects/Heros/11001/11001_battle_attack_passive_21_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 1,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010002] = {
		["CueID"] = 850010002,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "11001_battle_attack_passive_21",
			["SourcePath"] = "Effects/Heros/11001/11001_battle_attack_passive_21.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 1,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 3,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010003] = {
		["CueID"] = 850010003,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_11003_battle_attack_Smash_Hit_01",
			["SourcePath"] = "Effects/Heros/11003/efx_11003_battle_attack_Smash_Hit_01.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 1,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 1.5,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010004] = {
		["CueID"] = 850010004,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_11005_battle_attack_passive_01",
			["SourcePath"] = "Effects/Heros/11005/efx_11005_battle_attack_passive_01.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 1,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010005] = {
		["CueID"] = 850010005,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_11005_battle_attack_ultra_02",
			["SourcePath"] = "Effects/Heros/11005/efx_11005_battle_attack_ultra_02.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 1,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010006] = {
		["CueID"] = 850010006,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12004_battle_attack_passive_21_2",
			["SourcePath"] = "Effects/Heros/12004/efx_12004_battle_attack_passive_21_2.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 3,
			["offset"] ={["x"]=-4, ["y"]=0, ["z"]=0, },
			["scale"] = 2.5,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010007] = {
		["CueID"] = 850010007,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_33005_battle_attack_basic_01_1_behit",
			["SourcePath"] = "Effects/Heros/33005/efx_33005_battle_attack_basic_01_1_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 1,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010008] = {
		["CueID"] = 850010008,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13003_battle_attack_passive_22_02",
			["SourcePath"] = "Effects/Heros/13003/efx_13003_battle_attack_passive_22_02.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 1,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 1,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010009] = {
		["CueID"] = 850010009,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13003_battle_attack_ultra_51_3",
			["SourcePath"] = "Effects/Heros/13003/efx_13003_battle_attack_ultra_51_3.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 1,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010010] = {
		["CueID"] = 850010010,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13003_battle_attack_basic_01_behit",
			["SourcePath"] = "Effects/Heros/13003/efx_13003_battle_attack_basic_01_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010011] = {
		["CueID"] = 850010011,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14003_battle_attack_passive_21_behit",
			["SourcePath"] = "Effects/Heros/14003/efx_14003_battle_attack_passive_21_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 1,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010012] = {
		["CueID"] = 850010012,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_15001_battle_attack_ultra_behit",
			["SourcePath"] = "Effects/Heros/15001/efx_15001_battle_attack_ultra_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 1,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010013] = {
		["CueID"] = 850010013,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_15002_battle_attack_ultra_51_2",
			["SourcePath"] = "Effects/Heros/15002/efx_15002_battle_attack_ultra_51_2.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010014] = {
		["CueID"] = 850010014,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_15005_battle_attack_passive_01",
			["SourcePath"] = "Effects/Heros/15005/efx_15005_battle_attack_passive_01.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 1,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010015] = {
		["CueID"] = 850010015,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "1001_battle_attack_ultra_51_02",
			["SourcePath"] = "Assets/Res/Effects/Ultra_Effects/11001/1001_battle_attack_ultra_51_02.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 2,
			["speed"] = 1.5,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010016] = {
		["CueID"] = 850010016,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13003_battle_attack_ultra_51_3",
			["SourcePath"] = "Effects/Heros/13003/efx_13003_battle_attack_ultra_51_3.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 1,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 3,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010017] = {
		["CueID"] = 850010017,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_holy_2003",
			["SourcePath"] = "Effects/Heros/Common/efx_holy_2003.prefab",
			["howToPlay"] = 1,
			["playLength"] = -1,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010018] = {
		["CueID"] = 850010018,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_holy_2004",
			["SourcePath"] = "Effects/Heros/Common/efx_holy_2004.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010019] = {
		["CueID"] = 850010019,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_2005",
			["SourcePath"] = "Effects/Heros/Common/efx_common_2005.prefab",
			["howToPlay"] = 3,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010020] = {
		["CueID"] = 850010020,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_4001",
			["SourcePath"] = "Effects/Heros/Common/efx_common_4001.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Buff",
			["mountType"] = 1,
			["offset"] ={["x"]=0, ["y"]=1, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["startPos"] = "Bip001 Head",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010021] = {
		["CueID"] = 850010021,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_shield",
			["SourcePath"] = "Effects/Heros/Common/efx_common_shield.prefab",
			["howToPlay"] = 1,
			["playLength"] = 10,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010022] = {
		["CueID"] = 850010022,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_holy_4011_01",
			["SourcePath"] = "Effects/Heros/Common/efx_holy_4011_01.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 1,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010023] = {
		["CueID"] = 850010023,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_holy_4011_02",
			["SourcePath"] = "Effects/Heros/Common/efx_holy_4011_02.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Spine",
			["mountType"] = 1,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010024] = {
		["CueID"] = 850010024,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_holy_4017_01",
			["SourcePath"] = "Effects/Heros/Common/efx_holy_4017_01.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 1,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010025] = {
		["CueID"] = 850010025,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_holy_4017_02",
			["SourcePath"] = "Effects/Heros/Common/efx_holy_4017_02.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 1,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010026] = {
		["CueID"] = 850010026,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_holy_4020",
			["SourcePath"] = "Effects/Heros/Common/efx_holy_4020.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 3,
			["offset"] ={["x"]=-5, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010027] = {
		["CueID"] = 850010027,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_holy_4021",
			["SourcePath"] = "Effects/Heros/Common/efx_holy_4021.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Buff",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=1.2, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010028] = {
		["CueID"] = 850010028,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_holy_4023",
			["SourcePath"] = "Effects/Heros/Common/efx_holy_4023.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Buff",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=1, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010029] = {
		["CueID"] = 850010029,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_holy_4024",
			["SourcePath"] = "Effects/Heros/Common/efx_holy_4024.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Buff",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=1, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010030] = {
		["CueID"] = 850010030,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_heal_behit",
			["SourcePath"] = "Effects/Heros/Common/efx_common_heal_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010031] = {
		["CueID"] = 850010031,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13007_battle_attack_ultra_01_A",
			["SourcePath"] = "Effects/Heros/13007/efx_13007_battle_attack_ultra_01_A.prefab",
			["howToPlay"] = 0,
			["playLength"] = 0.65,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 2,
			["startPos"] = "Bip001 Spine",
			["endPos"] = "Bip001 Spine",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010032] = {
		["CueID"] = 850010032,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13007_battle_attack_ultra_01_behit_1",
			["SourcePath"] = "Effects/Heros/13007/efx_13007_battle_attack_ultra_01_behit_1.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Spine",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[850010033] = {
		["CueID"] = 850010033,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14011_battle_attack_basic_03_2",
			["SourcePath"] = "Effects/Heros/14011/efx_14011_battle_attack_basic_03_2.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 1.5,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "Bip001 Behit",
			["endPos"] = "Bip001 Behit",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
}
return Data
