local Data = {
	[10000021] = {
		["CueID"] = 10000021,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_ui_AVGExpression_01",
			["SourcePath"] = "Effects/UI/efx_ui_AVGExpression_01.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000003] = {
		["CueID"] = 10000003,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_stun",
			["SourcePath"] = "Effects/Heros/Common/efx_common_stun.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Buff",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000004] = {
		["CueID"] = 10000004,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000006] = {
		["CueID"] = 10000006,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["howToPlay"] = 0,
			["playLength"] = 0,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Head",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10005001] = {
		["CueID"] = 10005001,
		["CueType"] = 5,
		["TypeString"] = "PostProcess",
		["PostProcess"]= {
			["type"] = 6,
			["depthParam"]= {
				["focusDistance"] = 0.1,
				["aperture"] = 14.5,
				["focalLength"] = 300,
				["blurSize"] = 1,
			},
			["length"] = 0,
		},
	},
	[10000007] = {
		["CueID"] = 10000007,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_ui_universal",
			["SourcePath"] = "Effects/Scene/Battlefield/efx_ui_universal.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Head",
			["mountType"] = 4,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0.75,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000008] = {
		["CueID"] = 10000008,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_heal_behit02",
			["SourcePath"] = "Effects/Heros/Common/efx_common_heal_behit02.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10005002] = {
		["CueID"] = 10005002,
		["CueType"] = 5,
		["TypeString"] = "PostProcess",
		["PostProcess"]= {
			["type"] = 6,
			["depthParam"]= {
				["focusDistance"] = 9,
				["aperture"] = 15,
				["focalLength"] = 200,
				["blurSize"] = 1,
			},
			["length"] = 999,
			["cullingPlayer"] = 1,
		},
	},
	[10000009] = {
		["CueID"] = 10000009,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_GroupL_01",
			["SourcePath"] = "Effects/Heros/Common/efx_common_GroupL_01.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000010] = {
		["CueID"] = 10000010,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_GroupL_02",
			["SourcePath"] = "Effects/Heros/Common/efx_common_GroupL_02.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000011] = {
		["CueID"] = 10000011,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_GroupL_03",
			["SourcePath"] = "Effects/Heros/Common/efx_common_GroupL_03.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10002001] = {
		["CueID"] = 10002001,
		["CueType"] = 2,
		["TypeString"] = "GroupCue",
		["GroupCue"]= {
			["CueList"] = {10005003,10000012,},
		},
	},
	[10005003] = {
		["CueID"] = 10005003,
		["CueType"] = 5,
		["TypeString"] = "PostProcess",
		["PostProcess"]= {
			["type"] = 4,
			["tintColorParam"]= {
				["R"] = 0.1176471,
				["G"] = 0.1176471,
				["B"] = 0.1176471,
				["A"] = 255,
				["blendMode"] = false,
			},
			["length"] = 1.5,
			["cullingPlayer"] = 1,
		},
	},
	[10005004] = {
		["CueID"] = 10005004,
		["CueType"] = 5,
		["TypeString"] = "PostProcess",
		["PostProcess"]= {
			["type"] = 6,
			["depthParam"]= {
				["focusDistance"] = 12.5,
				["aperture"] = 32,
				["focalLength"] = 240,
				["blurSize"] = 0,
			},
			["length"] = 0,
		},
	},
	[10005005] = {
		["CueID"] = 10005005,
		["CueType"] = 5,
		["TypeString"] = "PostProcess",
		["PostProcess"]= {
			["type"] = 1,
			["bloomParam"]= {
				["intensity"] = 0.39,
				["threshold"] = 0.23,
				["softKnee"] = 0.5,
				["radius"] = 4,
				["useColorBloom"] = false,
				["colorBloomIntensity"] = 1,
				["colorBloomR"] = 0,
				["colorBloomG"] = 0,
				["colorBloomB"] = 0,
				["colorBloomBlurTheta"] = 2,
			},
			["length"] = 0,
		},
	},
	[10002002] = {
		["CueID"] = 10002002,
		["CueType"] = 2,
		["TypeString"] = "GroupCue",
		["GroupCue"]= {
			["CueList"] = {10005004,},
		},
	},
	[10000012] = {
		["CueID"] = 10000012,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_energy_hit",
			["SourcePath"] = "Effects/Heros/Common/efx_common_energy_hit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000022] = {
		["CueID"] = 10000022,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["OnlyAttacker"] = true,
		["EffectCue"]= {
			["Source"] = "efx_ui_AVGExpression_02",
			["SourcePath"] = "Effects/UI/efx_ui_AVGExpression_02.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10005006] = {
		["CueID"] = 10005006,
		["CueType"] = 5,
		["TypeString"] = "PostProcess",
		["PostProcess"]= {
			["type"] = 4,
			["tintColorParam"]= {
				["R"] = 1,
				["G"] = 1,
				["B"] = 1,
				["A"] = 255,
				["blendMode"] = false,
			},
			["fadeOut"] = 0.2,
			["length"] = 0.25,
		},
	},
	[10000001] = {
		["CueID"] = 10000001,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_buff_gainup",
			["SourcePath"] = "Effects/Heros/Common/efx_common_buff_gainup.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000023] = {
		["CueID"] = 10000023,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_buff_Armor",
			["SourcePath"] = "Effects/Heros/Common/efx_common_buff_Armor.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000024] = {
		["CueID"] = 10000024,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "11001_battle_attack_passive_21_behit",
			["SourcePath"] = "Effects/Heros/11001/11001_battle_attack_passive_21_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 1,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0.5,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000025] = {
		["CueID"] = 10000025,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_shield_02",
			["SourcePath"] = "Effects/Heros/Common/efx_common_shield_02.prefab",
			["howToPlay"] = 0,
			["playLength"] = 2.5,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10003001] = {
		["CueID"] = 10003001,
		["CueType"] = 3,
		["TypeString"] = "CueShake",
		["CueShake"]= {
			["Source"] = "X9MeleePunchShake01",
		},
	},
	[10001001] = {
		["CueID"] = 10001001,
		["CueType"] = 1,
		["TypeString"] = "Audio",
		["AudioCue"]= {
			["source"] = "hero_vocal_battle_commmon_51",
			["volume"] = 1,
			["pitch"] = 1,
			["priority"] = 128,
			["sourcePath"] = "Audios/SFX/Hero/hero_vocal_battle_commmon_51.ogg",
		},
	},
	[10005007] = {
		["CueID"] = 10005007,
		["CueType"] = 5,
		["TypeString"] = "PostProcess",
		["PostProcess"]= {
			["type"] = 8,
			["tonemappingParam"]= {
				["PostExposure"] = -0.7,
			},
			["length"] = 0,
		},
	},
	[10002003] = {
		["CueID"] = 10002003,
		["CueType"] = 2,
		["TypeString"] = "GroupCue",
		["GroupCue"]= {
			["CueList"] = {10005001,10005007,},
		},
	},
	[10002004] = {
		["CueID"] = 10002004,
		["CueType"] = 2,
		["TypeString"] = "GroupCue",
		["GroupCue"]= {
			["CueList"] = {10005002,10005007,},
		},
	},
	[10000026] = {
		["CueID"] = 10000026,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_frozen",
			["SourcePath"] = "Effects/Heros/Common/efx_common_frozen.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mountType"] = 2,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000027] = {
		["CueID"] = 10000027,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_Attack_speed_improvement",
			["SourcePath"] = "Effects/Heros/Common/efx_common_Attack_speed_improvement.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000028] = {
		["CueID"] = 10000028,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_Attack_speed_reduction",
			["SourcePath"] = "Effects/Heros/Common/efx_common_Attack_speed_reduction.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000029] = {
		["CueID"] = 10000029,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_Defense_enhancement_01",
			["SourcePath"] = "Effects/Heros/Common/efx_common_Defense_enhancement_01.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Behit",
			["mountType"] = 4,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 1.25,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000030] = {
		["CueID"] = 10000030,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_Defense_enhancement_02",
			["SourcePath"] = "Effects/Heros/Common/efx_common_Defense_enhancement_02.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000031] = {
		["CueID"] = 10000031,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_burning",
			["SourcePath"] = "Effects/Heros/Common/efx_common_burning.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000032] = {
		["CueID"] = 10000032,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_Sherbet",
			["SourcePath"] = "Effects/Heros/Common/efx_common_Sherbet.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000033] = {
		["CueID"] = 10000033,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_Invincible",
			["SourcePath"] = "Effects/Heros/Common/efx_common_Invincible.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Behit",
			["mountType"] = 4,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000034] = {
		["CueID"] = 10000034,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_Disarm",
			["SourcePath"] = "Effects/Heros/Common/efx_common_Disarm.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Buff",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=-0.25, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000035] = {
		["CueID"] = 10000035,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_Energy_recovery",
			["SourcePath"] = "Effects/Heros/Common/efx_common_Energy_recovery.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 1,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 2,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10006001] = {
		["CueID"] = 10006001,
		["CueType"] = 6,
		["TypeString"] = "ModelEffect",
		["ModelEffect"]= {
			["type"] = 2,
			["modelAddMaterial"]= {
				["part"] = "body",
				["materialPath"] = "Materials/T_Noise_025_01.mat",
			},
			["length"] = -1,
			["howToPlay"] = 2,
		},
	},
	[10006002] = {
		["CueID"] = 10006002,
		["CueType"] = 6,
		["TypeString"] = "ModelEffect",
		["ModelEffect"]= {
			["type"] = 2,
			["modelAddMaterial"]= {
				["part"] = "body",
				["materialPath"] = "Materials/T_Noise_030_03.mat",
			},
			["length"] = -1,
			["howToPlay"] = 2,
		},
	},
	[10002005] = {
		["CueID"] = 10002005,
		["CueType"] = 2,
		["TypeString"] = "GroupCue",
		["GroupCue"]= {
			["CueList"] = {10006001,10000031,},
		},
	},
	[10002006] = {
		["CueID"] = 10002006,
		["CueType"] = 2,
		["TypeString"] = "GroupCue",
		["GroupCue"]= {
			["CueList"] = {10000032,10006002,},
		},
	},
	[10000036] = {
		["CueID"] = 10000036,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14007_battle_attack_basic_bullet",
			["SourcePath"] = "Effects/Heros/14007/efx_14007_battle_attack_basic_bullet.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000037] = {
		["CueID"] = 10000037,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_holy_4024",
			["SourcePath"] = "Effects/Heros/Common/efx_holy_4024.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Buff",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=1, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000038] = {
		["CueID"] = 10000038,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_Immortal",
			["SourcePath"] = "Effects/Heros/Common/efx_common_Immortal.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000039] = {
		["CueID"] = 10000039,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_archer",
			["SourcePath"] = "Effects/Heros/Common/efx_common_archer.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 1,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000040] = {
		["CueID"] = 10000040,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_Energy_recovery",
			["SourcePath"] = "Effects/Heros/Common/efx_common_Energy_recovery.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000041] = {
		["CueID"] = 10000041,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_burning_behit",
			["SourcePath"] = "Effects/Heros/Common/efx_common_burning_behit.prefab",
			["howToPlay"] = 0,
			["playLength"] = 0,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000042] = {
		["CueID"] = 10000042,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_Sherbet_behit",
			["SourcePath"] = "Effects/Heros/Common/efx_common_Sherbet_behit.prefab",
			["howToPlay"] = 0,
			["playLength"] = 0,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000043] = {
		["CueID"] = 10000043,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_Battlefield_support_04",
			["SourcePath"] = "Effects/Scene/Battlefield/efx_Battlefield_support_04.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000044] = {
		["CueID"] = 10000044,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_career2_dodge",
			["SourcePath"] = "Effects/Heros/Common/efx_common_career2_dodge.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 1,
			["speed"] = 1,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000045] = {
		["CueID"] = 10000045,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_career5_heal_Supporter",
			["SourcePath"] = "Effects/Heros/Common/efx_common_career5_heal_Supporter.prefab",
			["howToPlay"] = 0,
			["playLength"] = 0.35,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Spine",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 2,
			["startPos"] = "Bip001 Spine",
			["endPos"] = "Bip001 Spine",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000046] = {
		["CueID"] = 10000046,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_career5_heal_Therapist",
			["SourcePath"] = "Effects/Heros/Common/efx_common_career5_heal_Therapist.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Spine",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10006003] = {
		["CueID"] = 10006003,
		["CueType"] = 6,
		["TypeString"] = "ModelEffect",
		["ModelEffect"]= {
			["type"] = 2,
			["modelAddMaterial"]= {
				["part"] = "body",
				["materialPath"] = "Materials/Behi_white.mat",
			},
			["length"] = 0.13,
			["howToPlay"] = 0,
		},
	},
	[10000047] = {
		["CueID"] = 10000047,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_heal_behit",
			["SourcePath"] = "Effects/Heros/Common/efx_common_heal_behit.prefab",
			["howToPlay"] = 0,
			["playLength"] = 0,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10006004] = {
		["CueID"] = 10006004,
		["CueType"] = 6,
		["TypeString"] = "ModelEffect",
		["ModelEffect"]= {
			["type"] = 5,
			["modelTransparency"]= {
				["alpha"] = 0.5,
			},
			["fadeIn"] = 0.05,
			["fadeOut"] = 0.05,
			["length"] = 0.3,
			["howToPlay"] = 0,
		},
	},
	[10000048] = {
		["CueID"] = 10000048,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_33003_battle_attack_passive_22_2",
			["SourcePath"] = "Effects/Heros/33003/efx_33003_battle_attack_passive_22_2.prefab",
			["howToPlay"] = 0,
			["playLength"] = 3,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0.55,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000049] = {
		["CueID"] = 10000049,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_33003_battle_attack_passive_22",
			["SourcePath"] = "Effects/Heros/33003/efx_33003_battle_attack_passive_22.prefab",
			["howToPlay"] = 0,
			["playLength"] = 2,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0.6,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000050] = {
		["CueID"] = 10000050,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_trap_101_behit",
			["SourcePath"] = "Effects/Heros/Common/efx_trap_101_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Spine",
			["mountType"] = 1,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000051] = {
		["CueID"] = 10000051,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_trap_102_buff",
			["SourcePath"] = "Effects/Heros/Common/efx_trap_102_buff.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000052] = {
		["CueID"] = 10000052,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_trap_201_buff",
			["SourcePath"] = "Effects/Heros/Common/efx_trap_201_buff.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000053] = {
		["CueID"] = 10000053,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_trap_202_buff",
			["SourcePath"] = "Effects/Heros/Common/efx_trap_202_buff.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000054] = {
		["CueID"] = 10000054,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_trap_203_buff",
			["SourcePath"] = "Effects/Heros/Common/efx_trap_203_buff.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Spine",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000055] = {
		["CueID"] = 10000055,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_trap_301_explode",
			["SourcePath"] = "Effects/Heros/Common/efx_trap_301_explode.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000056] = {
		["CueID"] = 10000056,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_trap_302_explode",
			["SourcePath"] = "Effects/Heros/Common/efx_trap_302_explode.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000057] = {
		["CueID"] = 10000057,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_trap_303_explode",
			["SourcePath"] = "Effects/Heros/Common/efx_trap_303_explode.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000058] = {
		["CueID"] = 10000058,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_trap_304_explode",
			["SourcePath"] = "Effects/Heros/Common/efx_trap_304_explode.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000059] = {
		["CueID"] = 10000059,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_trap_401_trigger",
			["SourcePath"] = "Effects/Heros/Common/efx_trap_401_trigger.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Spine",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000060] = {
		["CueID"] = 10000060,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_trap_402_trigger",
			["SourcePath"] = "Effects/Heros/Common/efx_trap_402_trigger.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000061] = {
		["CueID"] = 10000061,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_trap_403_trigger",
			["SourcePath"] = "Effects/Heros/Common/efx_trap_403_trigger.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10006005] = {
		["CueID"] = 10006005,
		["CueType"] = 6,
		["TypeString"] = "ModelEffect",
		["ModelEffect"]= {
			["type"] = 0,
			["modelScale"]= {
				["scale"] = 1.2,
				["mode"] = 0,
			},
			["fadeIn"] = 0.1,
			["fadeOut"] = 0.1,
			["length"] = -1,
			["howToPlay"] = 2,
		},
	},
	[10002007] = {
		["CueID"] = 10002007,
		["CueType"] = 2,
		["TypeString"] = "GroupCue",
		["GroupCue"]= {
			["CueList"] = {10000052,10006005,},
		},
	},
	[10006006] = {
		["CueID"] = 10006006,
		["CueType"] = 6,
		["TypeString"] = "ModelEffect",
		["ModelEffect"]= {
			["type"] = 1,
			["modelHide"]= {
				["hideHpLogo"] = true,
				["hideDamageNum"] = false,
				["skipHideModel"] = false,
			},
			["fadeOut"] = 100,
			["length"] = 1000,
			["howToPlay"] = 0,
		},
	},
	[10000062] = {
		["CueID"] = 10000062,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_behit_point",
			["SourcePath"] = "Effects/Heros/Common/efx_common_behit_point.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000063] = {
		["CueID"] = 10000063,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_behit_fire",
			["SourcePath"] = "Effects/Heros/Common/efx_common_behit_fire.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000064] = {
		["CueID"] = 10000064,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_behit_sharp",
			["SourcePath"] = "Effects/Heros/Common/efx_common_behit_sharp.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10005008] = {
		["CueID"] = 10005008,
		["CueType"] = 5,
		["TypeString"] = "PostProcess",
		["PostProcess"]= {
			["type"] = 2,
			["radialBlurParam"]= {
				["blurStrength"] = 5,
				["sampleDist"] = 0.5,
				["centerU"] = 0.5,
				["centerV"] = 0.5,
			},
			["length"] = 0.5,
		},
	},
	[10006007] = {
		["CueID"] = 10006007,
		["CueType"] = 6,
		["TypeString"] = "ModelEffect",
		["ModelEffect"]= {
			["type"] = 1,
			["modelHide"]= {
				["hideHpLogo"] = false,
				["hideDamageNum"] = false,
				["skipHideModel"] = false,
			},
			["length"] = -1,
			["howToPlay"] = 2,
		},
	},
	[10000065] = {
		["CueID"] = 10000065,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_timelock",
			["SourcePath"] = "Effects/Heros/Common/efx_common_timelock.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Buff",
			["mountType"] = 4,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000066] = {
		["CueID"] = 10000066,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_stun",
			["SourcePath"] = "Effects/Heros/Common/efx_common_stun.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Head",
			["mountType"] = 4,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10006008] = {
		["CueID"] = 10006008,
		["CueType"] = 6,
		["TypeString"] = "ModelEffect",
		["ModelEffect"]= {
			["type"] = 2,
			["modelAddMaterial"]= {
				["part"] = "all",
				["materialPath"] = "Materials/Stun_Material.mat",
			},
			["length"] = -1,
			["howToPlay"] = 2,
		},
	},
	[10002008] = {
		["CueID"] = 10002008,
		["CueType"] = 2,
		["TypeString"] = "GroupCue",
		["GroupCue"]= {
			["CueList"] = {10000065,10006008,},
		},
	},
	[10000067] = {
		["CueID"] = 10000067,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14010_battle_attack_basic_01_2",
			["SourcePath"] = "Effects/Heros/14010/efx_14010_battle_attack_basic_01_2.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "Bip001 R Hand/ST_RHand",
			["endPos"] = "Bip001 Behit",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000068] = {
		["CueID"] = 10000068,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14010_battle_attack_basic_01_2",
			["SourcePath"] = "Effects/Heros/14010/efx_14010_battle_attack_basic_01_2.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "Bip001 R Hand/ST_RHand",
			["endPos"] = "Bip001 Behit",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000069] = {
		["CueID"] = 10000069,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14010_battle_attack_basic_01_2",
			["SourcePath"] = "Effects/Heros/14010/efx_14010_battle_attack_basic_01_2.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "Bip001 Buff",
			["endPos"] = "Bip001 Behit",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10006009] = {
		["CueID"] = 10006009,
		["CueType"] = 6,
		["TypeString"] = "ModelEffect",
		["ModelEffect"]= {
			["type"] = 2,
			["modelAddMaterial"]= {
				["part"] = "body",
				["materialPath"] = "Materials/thunder_hit.mat",
			},
			["length"] = 0.3,
			["howToPlay"] = 0,
		},
	},
	[10005009] = {
		["CueID"] = 10005009,
		["CueType"] = 5,
		["TypeString"] = "PostProcess",
		["PostProcess"]= {
			["type"] = 8,
			["tonemappingParam"]= {
				["PostExposure"] = -0.3,
			},
			["length"] = 0,
		},
	},
	[10006010] = {
		["CueID"] = 10006010,
		["CueType"] = 6,
		["TypeString"] = "ModelEffect",
		["OnlyPlayer"] = true,
		["ModelEffect"]= {
			["type"] = 0,
			["modelScale"]= {
				["scale"] = 1.1,
				["mode"] = 0,
			},
			["fadeIn"] = 0.2,
			["fadeOut"] = 0.2,
			["length"] = -1,
			["howToPlay"] = 2,
		},
	},
	[10006011] = {
		["CueID"] = 10006011,
		["CueType"] = 6,
		["TypeString"] = "ModelEffect",
		["ModelEffect"]= {
			["type"] = 0,
			["modelScale"]= {
				["scale"] = 1.2,
				["mode"] = 0,
			},
			["fadeIn"] = 0.2,
			["fadeOut"] = 0.2,
			["length"] = -1,
			["howToPlay"] = 2,
		},
	},
	[10006012] = {
		["CueID"] = 10006012,
		["CueType"] = 6,
		["TypeString"] = "ModelEffect",
		["ModelEffect"]= {
			["type"] = 0,
			["modelScale"]= {
				["scale"] = 1.3,
				["mode"] = 0,
			},
			["fadeIn"] = 0.2,
			["fadeOut"] = 0.2,
			["length"] = -1,
			["howToPlay"] = 2,
		},
	},
	[10006013] = {
		["CueID"] = 10006013,
		["CueType"] = 6,
		["TypeString"] = "ModelEffect",
		["ModelEffect"]= {
			["type"] = 0,
			["modelScale"]= {
				["scale"] = 1.4,
				["mode"] = 0,
			},
			["fadeIn"] = 0.2,
			["fadeOut"] = 0.2,
			["length"] = -1,
			["howToPlay"] = 2,
		},
	},
	[10006014] = {
		["CueID"] = 10006014,
		["CueType"] = 6,
		["TypeString"] = "ModelEffect",
		["ModelEffect"]= {
			["type"] = 2,
			["modelAddMaterial"]= {
				["part"] = "all",
				["materialPath"] = "Materials/broken_Material.mat",
			},
			["length"] = -1,
			["howToPlay"] = 2,
		},
	},
	[10000070] = {
		["CueID"] = 10000070,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_charge",
			["SourcePath"] = "Effects/Heros/Common/efx_common_charge.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000071] = {
		["CueID"] = 10000071,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_archer_add",
			["SourcePath"] = "Effects/Heros/Common/efx_common_archer_add.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000072] = {
		["CueID"] = 10000072,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_redamage",
			["SourcePath"] = "Effects/Heros/Common/efx_common_redamage.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Buff",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000073] = {
		["CueID"] = 10000073,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14011_battle_attack_ultra_61_behit02",
			["SourcePath"] = "Effects/Heros/14011/efx_14011_battle_attack_ultra_61_behit02.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000074] = {
		["CueID"] = 10000074,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14011_battle_attack_passive_21_behit02",
			["SourcePath"] = "Effects/Heros/14011/efx_14011_battle_attack_passive_21_behit02.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000075] = {
		["CueID"] = 10000075,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_HeroEquipBgBox_snow",
			["SourcePath"] = "Effects/Scene/efx_HeroEquipBgBox_snow.prefab",
			["howToPlay"] = 3,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000076] = {
		["CueID"] = 10000076,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_Scene_Christmas01",
			["SourcePath"] = "Effects/Scene/efx_Scene_Christmas01.prefab",
			["howToPlay"] = 3,
			["playLength"] = -1,
			["loopTimes"] = 1,
			["mountType"] = 3,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=-5, },
			["scale"] = 0.7,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000077] = {
		["CueID"] = 10000077,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12012_battle_attack_ultra_61_debuff_behit",
			["SourcePath"] = "Effects/Heros/12012/efx_12012_battle_attack_ultra_61_debuff_behit.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10005010] = {
		["CueID"] = 10005010,
		["CueType"] = 5,
		["TypeString"] = "PostProcess",
		["PostProcess"]= {
			["type"] = 4,
			["tintColorParam"]= {
				["R"] = 0,
				["G"] = 0,
				["B"] = 0,
				["A"] = 255,
				["blendMode"] = false,
			},
			["length"] = 1,
			["cullingPlayer"] = 1,
		},
	},
	[10000078] = {
		["CueID"] = 10000078,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12003_battle_attack_ultra_04_new",
			["SourcePath"] = "Effects/Heros/12003/efx_12003_battle_attack_ultra_04_new.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000079] = {
		["CueID"] = 10000079,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_zhiyuan_03",
			["SourcePath"] = "Effects/Heros/Common/efx_common_zhiyuan_03.prefab",
			["howToPlay"] = 0,
			["playLength"] = 3,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 2,
			["startPos"] = "Bip001 Spine",
			["endPos"] = "Bip001 Spine",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000080] = {
		["CueID"] = 10000080,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_zhiyuan_02",
			["SourcePath"] = "Effects/Heros/Common/efx_common_zhiyuan_02.prefab",
			["howToPlay"] = 0,
			["playLength"] = 3,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Buff",
			["mountType"] = 4,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000081] = {
		["CueID"] = 10000081,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_12002_battle_attack_passive_21_1",
			["SourcePath"] = "Effects/Heros/12002/efx_12002_battle_attack_passive_21_1.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000082] = {
		["CueID"] = 10000082,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_13202_battle_attack_passive_21_2",
			["SourcePath"] = "Effects/Heros/13202/efx_13202_battle_attack_passive_21_2.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 1,
			["startPos"] = "Bip001 Spine",
			["endPos"] = "Bip001 Spine",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000083] = {
		["CueID"] = 10000083,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_common_poisoning",
			["SourcePath"] = "Effects/Heros/Common/efx_common_poisoning.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10006015] = {
		["CueID"] = 10006015,
		["CueType"] = 6,
		["TypeString"] = "ModelEffect",
		["ModelEffect"]= {
			["type"] = 2,
			["modelAddMaterial"]= {
				["part"] = "body",
				["materialPath"] = "Materials/poisoning_hit.mat",
			},
			["length"] = -1,
			["howToPlay"] = 2,
		},
	},
	[10002009] = {
		["CueID"] = 10002009,
		["CueType"] = 2,
		["TypeString"] = "GroupCue",
		["GroupCue"]= {
			["CueList"] = {10000083,10006015,},
		},
	},
	[10000084] = {
		["CueID"] = 10000084,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_14202_battle_attack_passive_21_1",
			["SourcePath"] = "Effects/Heros/14202/efx_14202_battle_attack_passive_21_1.prefab",
			["howToPlay"] = 1,
			["playLength"] = 0,
			["loopTimes"] = 1,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000085] = {
		["CueID"] = 10000085,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_15008_battle_attack_ultra_61_link",
			["SourcePath"] = "Effects/Heros/15008/efx_15008_battle_attack_ultra_61_link.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 2,
			["startPos"] = "Bip001 Spine",
			["endPos"] = "Bip001 Spine",
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000086] = {
		["CueID"] = 10000086,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_3310900_battle_attack_ultra_53_behit",
			["SourcePath"] = "Effects/Heros/33109/efx_3310900_battle_attack_ultra_53_behit.prefab",
			["howToPlay"] = 0,
			["playLength"] = 0,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Behit",
			["mountType"] = 2,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 1.5,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000087] = {
		["CueID"] = 10000087,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_trap_205_buff",
			["SourcePath"] = "Effects/Heros/Common/efx_trap_205_buff.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000088] = {
		["CueID"] = 10000088,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_trap_206_buff",
			["SourcePath"] = "Effects/Heros/Common/efx_trap_206_buff.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
	[10000089] = {
		["CueID"] = 10000089,
		["CueType"] = 0,
		["TypeString"] = "Effect",
		["EffectCue"]= {
			["Source"] = "efx_trap_207_buff",
			["SourcePath"] = "Effects/Heros/Common/efx_trap_207_buff.prefab",
			["howToPlay"] = 2,
			["playLength"] = -1,
			["loopTimes"] = 0,
			["mount"] = "Bip001 Behit",
			["mountType"] = 0,
			["offset"] ={["x"]=0, ["y"]=0, ["z"]=0, },
			["scale"] = 0,
			["speed"] = 0,
			["motionMode"] = 0,
			["height"] = 0,
			["curve"] = 0,
			["oppositeDirection"] = false,
		},
	},
}
return Data
